### ISSUE TITLE
throw new QueryRunnerAlreadyReleasedError()

### ISSUE THREAD

**Issue by onursonmez** [vendure-ecommerce/vendure#2868] opened 2024-05-27 19:28 UTC
I developed the Wishlist plugin located at https://docs.vendure.io/guides/developer-guide/plugins/. When I successively click on the Login, AddtoWishlist, GetWishlist, RemoveFromWishlist mutations from the http://localhost:3000/shop-api screen, Vendure Server crashes and I get the error in the screenshot below.

**To Reproduce**
Enter the http://localhost:3000/shop-api screen and prepare 4 mutations that log in, insert, get and remove. Run these mutations one after another by pressing the play button. Vendure Server will crash.

**Expected behavior**
Vendure Server should not crash due to Postgresql in consecutive queries.

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.4
 - Nodejs version v18.20.0
 - Database (mysql/postgres etc): postgresql
<img width="1440" alt="Screenshot 2024-05-27 at 22 27 27" src="https://github.com/vendure-ecommerce/vendure/assets/7568973/7a5c778b-92a7-4e9c-9d05-c1e3182f36d9">
<img width="985" alt="Screenshot 2024-05-27 at 22 27 44" src="https://github.com/vendure-ecommerce/vendure/assets/7568973/4cc87919-c630-4781-9cf7-00e295f4a16f">

**Comment by onursonmez** [comment] 2024-05-27 20:52
```
@Mutation()
@Transaction()
```

It was fixed when I changed the above code in the wishlist.resolver.ts file as follows, that is, deleted the @Transaction() part.

`@Mutation()`

Do you have any idea why he's doing this? Is @Transaction expecting multiple triggers?

**Comment by michaelbromley** [comment] 2024-06-03 11:47
Hi,

The solution should not be to remove the `@Transaction()` decorator, since we _do_ generally want mutations to run inside transactions. I'm not sure how it is that running the mutations one after the other causes the issue you reported. I'll see if I can reproduce.

**Comment by michaelbromley** [comment] 2024-06-03 11:57
I am not able to reproduce this (see screen recording). 


https://github.com/vendure-ecommerce/vendure/assets/6275952/a72cf50a-2a98-4ff0-a409-acb9fe7f6250

**Comment by Rana-Faraz** [comment] 2024-11-27 11:53
If you run the `addToWhishlist` mutation twice then the server crashes with the given error. 

in simple words 
- If the variant is already in the wishlist and you run the query again the server crashes

**Comment by michaelbromley** [comment] 2024-11-29 12:38
Fixed in https://github.com/vendure-ecommerce/vendure/pull/3242

**Closed by michaelbromley** 2024-11-29 12:38 UTC
Labels: type: bug 🐛
