### ISSUE TITLE
npx vendure add Manipulation error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by DanZmanGrant** [vendure-ecommerce/vendure#2817] opened 2024-04-27 06:37 UTC
**Describe the bug**
Trying to add a plugin using the new CLI tool from a clean install of Vendure 2.2.2 resulted in the following error… **Manipulation error: Maximum call stack size exceeded** 

I first encountered the issue when I upgraded my project from Vendure 2.1.8 to 2.2.2 and installed the new CLI tool. I then did a clean install, which resulted in the same error.

![image](https://github.com/vendure-ecommerce/vendure/assets/161900127/a45cb8a5-eb6a-41f5-bf43-d90dab03eb4f)

**To Reproduce**
1. npx @vendure/create my-shop (using defaults with SQLite for testing)
2. cd my-shop
3. npm run dev
4. Stopped server
5. npx vendure add
6. Followed by the below steps (taken straight from the docs and the Vendure CLI video)… 

![image](https://github.com/vendure-ecommerce/vendure/assets/161900127/081f58be-7d5b-4fd7-bc92-5ea9c7f9c23e)

**Expected behavior**
I expected to see the following: 

- Generated plugin scaffold
- Updated VendureConfig
- A prompt asking **Add features to cms?** with available options.

**Environment (please complete the following information):**
 - @vendure/core version: 2.2.2
 - Nodejs version: v20.10.0
 - Database: SQLite
 - OS: macOS Sonoma 14.4.1
 - Hardware: Apple M2 (Mac mini 2023)

**Additional context**
Text version of error…
Manipulation error: Maximum call stack size exceeded
│  
│  -- Details --
│  Path: /Users/dangrant/Documents/Vendure/my-shop/src/plugins/cms/cms.plugin.ts
│  Text: "import { PluginCommonModule, Type, VendurePlugin } from '@vendure/core';\r\n\r\nimport { CMS_PLUGIN_OPTIONS } from './constants.template';\r\nimport { PluginInitOptions } from '../../Users/dangrant/Documents/Vendure/my-shop/src/plugins/cms/types';\r\n\r\n@VendurePlugin({\r\n    imports: [PluginCommonModule],\r\n    providers: [{ provide: CMS_PLUGIN_OPTIONS, useFactory: () => CmsPlugin.options }],\r\n    configuration: config => {\r\n        // Plugin-specific configuration\r\n        // such as custom fields, custom permissions,\r\n        // strategies etc. can be configured here by\r\n        // modifying the `config` object.\r\n        return config;\r\n    },\r\n    compatibility: '^2.0.0',\r\n})\r\nexport class CmsPlugin {\r\n    static options: PluginInitOptions;\r\n\r\n    static init(options: PluginInitOptions): Type<CmsPlugin> {\r\n        this.options = options;\r\n        return CmsPlugin;\r\n    }\r\n}\r\n"
│  Stack: RangeError: Maximum call stack size exceeded
│      at RealFileSystemHost.directoryExistsSync (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/ts-morph-common.js:1955:24)
│      at TransactionalFileSystem.directoryExistsSync (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/ts-morph-common.js:2464:33)
│      at Object.directoryExists (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/ts-morph-common.js:1392:44)
│      at Object.directoryExists (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/ts-morph-common.js:1420:57)
│      at directoryProbablyExists (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:17066:42)
│      at tryAddingExtensions (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:40666:31)
│      at loadModuleFromFile (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:40630:41)
│      at loader (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:41565:81)
│      at loadModuleFromSpecificNodeModulesDirectory (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:41605:12)
│      at loadModuleFromImmediateNodeModulesDirectory (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:41525:29)
│
■  Error: Manipulation error: Maximum call stack size exceeded
│  
│  -- Details --
│  Path: /Users/dangrant/Documents/Vendure/my-shop/src/plugins/cms/cms.plugin.ts
│  Text: "import { PluginCommonModule, Type, VendurePlugin } from '@vendure/core';\r\n\r\nimport { CMS_PLUGIN_OPTIONS } from './constants.template';\r\nimport { PluginInitOptions } from '../../Users/dangrant/Documents/Vendure/my-shop/src/plugins/cms/types';\r\n\r\n@VendurePlugin({\r\n    imports: [PluginCommonModule],\r\n    providers: [{ provide: CMS_PLUGIN_OPTIONS, useFactory: () => CmsPlugin.options }],\r\n    configuration: config => {\r\n        // Plugin-specific configuration\r\n        // such as custom fields, custom permissions,\r\n        // strategies etc. can be configured here by\r\n        // modifying the `config` object.\r\n        return config;\r\n    },\r\n    compatibility: '^2.0.0',\r\n})\r\nexport class CmsPlugin {\r\n    static options: PluginInitOptions;\r\n\r\n    static init(options: PluginInitOptions): Type<CmsPlugin> {\r\n        this.options = options;\r\n        return CmsPlugin;\r\n    }\r\n}\r\n"
│  Stack: RangeError: Maximum call stack size exceeded
│      at RealFileSystemHost.directoryExistsSync (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/ts-morph-common.js:1955:24)
│      at TransactionalFileSystem.directoryExistsSync (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/ts-morph-common.js:2464:33)
│      at Object.directoryExists (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/ts-morph-common.js:1392:44)
│      at Object.directoryExists (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/ts-morph-common.js:1420:57)
│      at directoryProbablyExists (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:17066:42)
│      at tryAddingExtensions (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:40666:31)
│      at loadModuleFromFile (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:40630:41)
│      at loader (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:41565:81)
│      at loadModuleFromSpecificNodeModulesDirectory (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:41605:12)
│      at loadModuleFromImmediateNodeModulesDirectory (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@ts-morph/common/dist/typescript.js:41525:29)
│      at throwError (/Users/dangrant/Documents/Vendure/my-shop/node_modules/ts-morph/dist/ts-morph.js:2375:19)
│      at doManipulation (/Users/dangrant/Documents/Vendure/my-shop/node_modules/ts-morph/dist/ts-morph.js:2373:9)
│      at replaceSourceFileForFilePathMove (/Users/dangrant/Documents/Vendure/my-shop/node_modules/ts-morph/dist/ts-morph.js:2801:5)
│      at SourceFile._moveInternal (/Users/dangrant/Documents/Vendure/my-shop/node_modules/ts-morph/dist/ts-morph.js:13424:9)
│      at SourceFile.move (/Users/dangrant/Documents/Vendure/my-shop/node_modules/ts-morph/dist/ts-morph.js:13400:19)
│      at generatePlugin (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@vendure/cli/dist/commands/add/plugin/create-new-plugin.js:184:16)
│      at async Object.createNewPlugin [as run] (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@vendure/cli/dist/commands/add/plugin/create-new-plugin.js:90:54)
│      at async addCommand (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@vendure/cli/dist/commands/add/add.js:47:50)
│      at async Command.<anonymous> (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@vendure/cli/dist/cli.js:52:5)
│      at async Command.parseAsync (/Users/dangrant/Documents/Vendure/my-shop/node_modules/@vendure/cli/node_modules/commander/lib/command.js:936:5)
│
└  ❌ Error

◇  Canceled

**Comment by hammadsanaullah** [comment] 2024-04-30 02:33
The same issue happens with me as well, can't create new plugin using the cli

`◒  Generating plugin scaffold│
■  Manipulation error: Maximum call stack size exceeded
│  
│  -- Details --
│  Path: /alcosta-vendure/src/plugins/my-new-feature/my-new-feature.plugin.ts
│  Text: "import { PluginCommonModule, Type, VendurePlugin } from '@vendure/core';\r\n\r\nimport { MY_NEW_FEATURE_PLUGIN_OPTIONS } from './constants.template';\r\nimport { PluginInitOptions } from '../../alcosta-vendure/src/plugins/my-new-feature/types';\r\n\r\n@VendurePlugin({\r\n    imports: [PluginCommonModule],\r\n    providers: [{ provide: MY_NEW_FEATURE_PLUGIN_OPTIONS, useFactory: () => MyNewFeaturePlugin.options }],\r\n    configuration: config => {\r\n        // Plugin-specific configuration\r\n        // such as custom fields, custom permissions,\r\n        // strategies etc. can be configured here by\r\n        // modifying the `config` object.\r\n        return config;\r\n    },\r\n    compatibility: '^2.0.0',\r\n})\r\nexport class MyNewFeaturePlugin {\r\n    static options: PluginInitOptions;\r\n\r\n    static init(options: PluginInitOptions): Type<MyNewFeaturePlugin> {\r\n        this.options = options;\r\n        return MyNewFeaturePlugin;\r\n    }\r\n}\r\n"
│  Stack: RangeError: Maximum call stack size exceeded
│      at Object.getCanonicalFileName (/alcosta-vendure/node_modules/@ts-morph/common/dist/ts-morph-common.js:1416:31)
│      at getCanonicalFileName (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:121251:19)
│      at toPath (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:6823:12)
│      at Object.getPackageJsonInfo2 [as getPackageJsonInfo] (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:39877:49)
│      at getPackageJsonInfo (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:40889:78)
│      at loadModuleFromSpecificNodeModulesDirectory (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:41548:23)
│      at loadModuleFromImmediateNodeModulesDirectory (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:41525:29)
│      at /alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:41513:33
│      at forEachAncestorDirectory (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:6975:22)
│      at lookup (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:41507:14)
│
■  Error: Manipulation error: Maximum call stack size exceeded
│  
│  -- Details --
│  Path: /alcosta-vendure/src/plugins/my-new-feature/my-new-feature.plugin.ts
│  Text: "import { PluginCommonModule, Type, VendurePlugin } from '@vendure/core';\r\n\r\nimport { MY_NEW_FEATURE_PLUGIN_OPTIONS } from './constants.template';\r\nimport { PluginInitOptions } from '../../alcosta-vendure/src/plugins/my-new-feature/types';\r\n\r\n@VendurePlugin({\r\n    imports: [PluginCommonModule],\r\n    providers: [{ provide: MY_NEW_FEATURE_PLUGIN_OPTIONS, useFactory: () => MyNewFeaturePlugin.options }],\r\n    configuration: config => {\r\n        // Plugin-specific configuration\r\n        // such as custom fields, custom permissions,\r\n        // strategies etc. can be configured here by\r\n        // modifying the `config` object.\r\n        return config;\r\n    },\r\n    compatibility: '^2.0.0',\r\n})\r\nexport class MyNewFeaturePlugin {\r\n    static options: PluginInitOptions;\r\n\r\n    static init(options: PluginInitOptions): Type<MyNewFeaturePlugin> {\r\n        this.options = options;\r\n        return MyNewFeaturePlugin;\r\n    }\r\n}\r\n"
│  Stack: RangeError: Maximum call stack size exceeded
│      at Object.getCanonicalFileName (/alcosta-vendure/node_modules/@ts-morph/common/dist/ts-morph-common.js:1416:31)
│      at getCanonicalFileName (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:121251:19)
│      at toPath (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:6823:12)
│      at Object.getPackageJsonInfo2 [as getPackageJsonInfo] (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:39877:49)
│      at getPackageJsonInfo (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:40889:78)
│      at loadModuleFromSpecificNodeModulesDirectory (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:41548:23)
│      at loadModuleFromImmediateNodeModulesDirectory (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:41525:29)
│      at /alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:41513:33
│      at forEachAncestorDirectory (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:6975:22)
│      at lookup (/alcosta-vendure/node_modules/@ts-morph/common/dist/typescript.js:41507:14)
│      at throwError (/alcosta-vendure/node_modules/ts-morph/dist/ts-morph.js:2375:19)
│      at doManipulation (/alcosta-vendure/node_modules/ts-morph/dist/ts-morph.js:2373:9)
│      at replaceSourceFileForFilePathMove (/alcosta-vendure/node_modules/ts-morph/dist/ts-morph.js:2801:5)
│      at SourceFile._moveInternal (/alcosta-vendure/node_modules/ts-morph/dist/ts-morph.js:13424:9)
│      at SourceFile.move (/alcosta-vendure/node_modules/ts-morph/dist/ts-morph.js:13400:19)
│      at generatePlugin (/alcosta-vendure/node_modules/@vendure/cli/dist/commands/add/plugin/create-new-plugin.js:184:16)
│      at async Object.createNewPlugin [as run] (/alcosta-vendure/node_modules/@vendure/cli/dist/commands/add/plugin/create-new-plugin.js:90:54)
│      at async addCommand (/alcosta-vendure/node_modules/@vendure/cli/dist/commands/add/add.js:47:50)
│      at async Command.<anonymous> (/alcosta-vendure/node_modules/@vendure/cli/dist/cli.js:52:5)
│      at async Command.parseAsync (/alcosta-vendure/node_modules/@vendure/cli/node_modules/commander/lib/command.js:936:5)
│
└  ❌ Error

◇  Canceled
✨  Done in 10.52s.`

**Comment by michaelbromley** [comment] 2024-04-30 07:01
Closing as duplicate of 

- #2819

Will track the fix in that issue.

**Closed by michaelbromley** 2024-04-30 07:01 UTC
Labels: type: bug 🐛
