### ISSUE TITLE
Custom Field into Core Section instead of Custom Field Section

### ISSUE THREAD

**Issue by OwlthTech** [vendure-ecommerce/vendure#2751] opened 2024-03-27 11:59 UTC
**Is your feature request related to a problem? Please describe.**
Trying to add custom field into Price and tax section. Need to add M.R.P of the product, not into Custom Field section, but at the relevant place of core/default section.

**Describe the solution you'd like**
Using customFields, it adds fields creating separate section "Custom Fields", trying to fiend a way to include custom fields in default sections.

**Additional context**
I tried finding in documents to add custom fields in native/core/default section, but doesn't find any.

**Comment by michaelbromley** [comment] 2024-06-20 12:01
Hi, this is not currently supported.

Closing as a duplicate of:

- #2409

**Closed by michaelbromley** 2024-06-20 12:01 UTC
