### ISSUE TITLE
No price found for channel

### ISSUE THREAD

**Issue by loan9202** [vendure-ecommerce/vendure#428] opened 2020-08-01 03:26 UTC
**To Reproduce**
1. Go to Product
2. Click on Add new
3. Input Product name is Test
4. Input variant:
- size: s, m, l
- color: white, blue
5. Input sku in each variants

**Expected behavior**
When I query product contains name is Test, I will get product Test

**Environment (please complete the following information):**
 - @vendure/core version: 0.14
 - Nodejs version: v14.6.0
 - Database (mysql/postgres etc): sqlite
![Screenshot from 2020-07-31 13-24-21](https://user-images.githubusercontent.com/51982365/89093093-6ee7aa80-d3e1-11ea-968a-edbf3a294da6.png)

**Comment by michaelbromley** [comment] 2020-08-18 11:10
Hi @loan9202 

I just followed the steps you describe in the issue on the current master branch, and cannot reproduce the issue. Can you provide any more context that might help me reproduce? E.g. do you have more than 1 channel set up?

**Comment by michaelbromley** [comment] 2020-08-31 10:20
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Closed by michaelbromley** 2020-08-31 10:20 UTC
Labels: type: bug 🐛
