### ISSUE TITLE
Cannot compile admin UI with 2.0.0-next.27

### ISSUE THREAD

**Issue by martijnvdbrug** [vendure-ecommerce/vendure#1959] opened 2023-01-02 14:39 UTC
**Describe the bug**
Admin UI compilation, without any customization, fails with 2.0.0-next.27.

**To Reproduce**
1. Add `compileUiExtensions` to your vendure-config with the following settings:
```
      AdminUiPlugin.init({
        port: 3002,
        route: 'admin',
        app: compileUiExtensions({
          outputPath: path.join(__dirname, '__admin-ui'),
          extensions: [],
          devMode: true
        }),
      }),
```      
2. Start Vendure with `yarn ts-node index.ts`
3. See error: `Unknown option: '--base-href'`

**Expected behavior**
I would expect the Admin UI to run in dev-mode, even without customized extensions.

Also, `devMode: false` fails because Angular complains about everything in node_modules, but that might be a different issue.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0-next.27
 - Nodejs version: 16
 - Database (mysql/postgres etc): sqlite
 - Typescript 4.5.5

**Additional context**
Yes, I have deleted yarn.lock and node_modules several times :upside_down_face:

**Comment by michaelbromley** [comment] 2023-01-02 20:30
Duplicate of #1794

**Closed by michaelbromley** 2023-01-02 20:30 UTC
Labels: type: bug 🐛
