### ISSUE TITLE
Missing TypeORM repository for GlobalSettings in the EventBus handler

### ISSUE THREAD

**Issue by McHunkyTrunk** [vendure-ecommerce/vendure#370] opened 2020-06-10 12:13 UTC
**Describe the bug**
When registering an event bus handler in the `onVendureBootstrap()` method of a custom plugin, an exception is thrown for `this.connection.getRepository(GlobalSettings)`, saying:
```
UnhandledPromiseRejectionWarning: RepositoryNotFoundError: No repository for "undefined" was found. Looks like this entity is not registered in current "default" connection?
```

**To Reproduce**
1. Create a custom plugin:
```
@VendurePlugin({
  imports: [PluginCommonModule]
})
export class CustomPlugin implements OnVendureBootstrap {
  constructor(
    private eventBus: EventBus,
    @InjectConnection() private connection: Connection
  ) {}

  onVendureBootstrap() {
    this.eventBus.ofType(PaymentStateTransitionEvent).subscribe(event => {
      const repository = this.connection.getRepository(GlobalSettings);
    }
  }
}
```
2. Register plugin in the config.
3. Restart the server.
4. See error.

**Expected behavior**
A GlobalSettings repository is expected.

**Environment:**
 - @vendure/core version: 0.12.5
 - Nodej: 12.16.2
 - Database: postgres

**Comment by michaelbromley** [comment] 2020-06-11 11:43
Very strange. So the root issue is that when importing

```ts
import { GlobalSettings } from '@vendure/core';
```
the `GlobalSettings` class is `undefined`. 

If importing from  
```ts
import { GlobalSettings } from '@vendure/core/dist/entity/global-settings/global-settings.entity';
```
it works as expected. Need to do more investigation to figure out why this is.

**Comment by michaelbromley** [comment] 2021-11-08 12:24
Closing this as there have been no other reports since, and I cannot reproduce on the current master branch.

**Closed by michaelbromley** 2021-11-08 12:24 UTC
Labels: type: bug 🐛, @vendure/core
