### ISSUE TITLE
Cannot properly create new multilanguage products

### ISSUE THREAD

**Issue by artcoded-dev** [vendure-ecommerce/vendure#1002] opened 2021-07-23 15:23 UTC
**Describe the bug**
Multilingual product creation doesn't work, as variant is created only in the first language selected (not replicated in the others)

**To Reproduce**
1. Go to the admin panel's product view and create a new product in the default language (e.g. Italian) with a name, slug, single option & option value and sku details (including price)
2. Click on create: the product is now created correctly with 1 variant
3. Switch to another language (e.g. English): the product is empty, so we fill name and slug (that are different because of the different language)
4. The checkbox to keep variant names synced appears: we keep it flagged and click on Update
5. The product gets saved, but under variants the table is empty
6. Visiting the Manage Variants section actually shows the variant created in the first language, but without sku and with price at 0: trying to fill this information and saving results in an error: `A ProductVariant with the selected options already exists`

**Expected behavior**
Creating a product translation in a second (or _nth_) language should result in properly creating a variant translation in that language as well, based on existing product option settings

**Environment (please complete the following information):**
 - @vendure/core version: 1.1.0 running in serverless environment (Google Cloud Run)
 - Nodejs version: 14
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment] 2021-07-26 08:59
Hi,

I _think_ this got resolved in v1.1.1. I followed the repro steps on current master and it seems ok. Can you update your version and try again?

**Comment by artcoded-dev** [comment] 2021-08-09 15:44
Hi, sorry for the delay, I had the chance to update and test again only today. I am now using v 1.1.3 and:
- the blocking error doesn't happen anymore!
- but, while creating the product in the default language also automatically populates the variant name, when creating the "secondary language" counterpart, it does create the corresponding variant, but does NOT populate the variant name, even if I left the box for syncing variant names checked
This is still a big issue for multi-language sites like mine, as it requires to manually fill each variant name

**Comment by michaelbromley** [comment] 2021-08-18 11:31
Hi,

Glad that the original issue is resolved.

Your second point seems like a separate (but related) issue.

Let's say I have 2 languages, English (default) and German.

I create a new product, "Shirt" with 2 options, "small" ,"large". When I create it, I get 2 variants named "Shirt small" and "Shirt large".

Now I go to the product details tab and switch to German and fill in the name as "Hemd" and click save.

What should happen?

Automatically set the variant names to "Hemd small" and "Hemd large"? This is only partially useful as the option names are not yet translated. But then by editing the option name it could automatically update the variant name. Is that the workflow you have in mind?

**Comment by artcoded-dev** [comment] 2021-08-19 09:02
Hi,
Yes now this is basically the same issue as #600, which I opened. So if you want you can close this.
By the way, to mention the real use case, my customer uses the option "size" for all products, and values are like 100g, 500g, 1kg, etc. So what I would expect is that the new variant, instead of getting an empty name, is automatically called <product name> <size value>, e.g. Italian Pasta 100g.
Thanks

**Comment by michaelbromley** [comment] 2021-08-19 09:04
OK thanks for the clarification. I will close this now and track the other issue in 600. Now I understand better what the problem is with that issue, so I'll see if I can resolve that one quickly.

**Closed by michaelbromley** 2021-08-19 09:04 UTC
Labels: type: bug 🐛
