### ISSUE TITLE
When a product has 0 Product Variants, I am not allowed to add 1 Product Variant without any Product Options groups defined

### ISSUE THREAD

**Issue by Caryntjen** [vendure-ecommerce/vendure#2522] opened 2023-11-11 15:57 UTC
**Describe the bug**
If I have a product with 1 product variant and I remove the 1 product variant to add a new one, this is not allowed by the Admin UI:

I get the following message:
'Product variants cannot be created until an option group with at least two product options has been defined

While I do not want to add 2 Product variants, I just want exactly 1. I am being restricted to add 1.

**To Reproduce**
1. Create new product with 1 variant and no Product Options
2. Delete product variant
3. Try to add only 1 variant without any Product Options available

Additionally:
Let's say you did define 2 Product optioins and a product has 1 product option defined with 2 values, but the product has 0 product variants, it is not possible to add a product:

' ProductVariant optionIds must include one optionId from each of the groups: test'

**Expected behavior**
I am allowed to add 1 product variant if there are 0 products variants, if there were 1 product variant available, I would need to define a product variant.

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.2
 - Nodejs version: v16.15.1
 - Database (mysql/postgres etc): Postgress

**Additional context**
I reported this as a bug, but it might be considered a new feature.

**Comment by michaelbromley** [comment] 2023-11-13 09:27
Hi! Thanks for the report. This appears to be a duplicate of #2507 which already has a fix coming in the next patch 👍

**Closed by michaelbromley** 2023-11-13 09:27 UTC
Labels: type: bug 🐛
