### ISSUE TITLE
The order has been paid and the status is paymentauthorized. Click Modify order, and the page does not jump to the edit page

### ISSUE THREAD

**Issue by skyearthfeng** [vendure-ecommerce/vendure#1032] opened 2021-08-13 04:32 UTC
**Describe the bug**
The order has been paid and the status is paymentauthorized. Click Modify order, and the page does not jump to the edit page
Browser development tool display error:
![新建位图图像 (3)](https://user-images.githubusercontent.com/2148134/129305002-a51d23b0-3dae-4608-a632-c32e010078c1.png)

**To Reproduce**

**Expected behavior**
the page does not jump to the edit page

**Environment (please complete the following information):**
 - @vendure/core version:10.2.2
 - Nodejs version:v12.22.1
 - Database (mysql/postgres etc):sqlite

**Additional context**

**Comment by skyearthfeng** [comment] 2021-08-17 08:57
The problem has been found. Just modify it as follows：
![1629190484(1)](https://user-images.githubusercontent.com/2148134/129695697-3582cb80-99ae-480d-bf1a-918f89a1a550.png)

**Comment by michaelbromley** [comment] 2021-08-18 11:03
Hi, I cannot reproduce this on the current latest version 1.1.3.

In your report you put the Vendure version as `@vendure/core version:10.2.2`. This is not a valid version - can you check again?

**Comment by skyearthfeng** [comment] 2021-08-19 04:28
Sorry, @ vendure / core version: 10.2.2, wrong. It should be @ vendure / core version: 1.1.3. 

My browser is:：
    Microsoft Edge
    版本 92.0.902.73 (官方内部版本) (64 位)

**Comment by skyearthfeng** [comment] 2021-08-19 05:31
The same problem is tested in chrome v92.0.4515.159 browser
![新建位图图像 (5)](https://user-images.githubusercontent.com/2148134/130008526-487f6dc5-df5f-488d-9e19-179ff5f4a778.png)

**Comment by michaelbromley** [comment] 2021-08-19 13:38
Ok. Looks like it could be related to https://github.com/apollographql/apollo-client/issues/7608

Can you tell me the exact version of Apollo Client installed using `npm ls @apollo/client`?

**Comment by skyearthfeng** [comment] 2021-08-20 11:08
"name": "@apollo/client",
  "version": "3.3.11",
  "description": "A fully-featured caching GraphQL client.",

**Comment by michaelbromley** [comment] 2021-09-23 12:30
Hi, sorry about the long delay on getting back on this. I have been doing some reading and it seems there can be memory leak issues with `shareReplay`:

* https://ncjamieson.com/avoiding-takeuntil-leaks/
* https://ncjamieson.com/whats-changed-with-sharereplay/
* https://blog.strongbrew.io/share-replay-issue/

The advice seemed conflicting on whether it is better to put the `takeUntil` _before_ or _after_ the `shareReplay` operator.

Could you try this change, and let me know if it also solves the issue?

```diff
    const stream = this.entityStream(id || '').pipe(
                takeUntil(navigateAway$),
                filter(notNullOrUndefined),
-               shareReplay(1),
+               shareReplay({ bufferSize: 1, refCount: true }),
```

**Comment by michaelbromley** [comment] 2022-02-21 20:24
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Closed by michaelbromley** 2022-02-21 20:24 UTC
Labels: type: bug 🐛
