### ISSUE TITLE
Price with tax incorrect while using BigInt strategy

### ISSUE THREAD

**Issue by daniel-lxs** [vendure-ecommerce/vendure#2527] opened 2023-11-15 00:01 UTC
**Describe the bug**
The property of ProductVariant priceWithTax is not being correctly calculated while using BigInt strategy for prices, priceWithTax is a concatenation of the price of the product variant and the calculated tax percentage of that price.

**To Reproduce**
1. Import and use BigIntMoneyStrategy
2. Add Tax value on the Vendure admin dashbboard
3.  Go to product variants to check the prices
4. See error on the price presented by the dashboard

**Expected behavior**
The price with tax should be the sum of the numbers and not the concatenation of the 2 values as if they were a string.

**Environment:**
 - @vendure/core : v2.1.1
 - Node: v18
 - Database: mysql
 

**Additional context**
![msg-1001616204137-37460](https://github.com/vendure-ecommerce/vendure/assets/57051444/3125c1b1-070a-488e-8baf-551944649360)

**Comment by michaelbromley** [comment] 2023-11-15 09:49
Hi,

I am not able to reproduce this so far. Can you clarify what you mean by this step?

> Add Tax value on the Vendure admin dashbboard

**Comment by alebak** [comment] 2023-11-15 15:41
Hi @michaelbromley, @daniel-lxs indicates is that you add or adjust the value on the tax page. In Colombia the tax is 19%.

![image](https://github.com/vendure-ecommerce/vendure/assets/6515879/11d4b390-d1e5-4981-a112-012c7bc86155)

So the second step was to adjust that value:

![image](https://github.com/vendure-ecommerce/vendure/assets/6515879/13dec1c0-aabb-4917-9e1b-5652e5f00d2f)

Once the tax has been adjusted. When checking the product and its variants, this price with tax appears in the admin-ui:

![image](https://github.com/vendure-ecommerce/vendure/assets/6515879/a998b71f-623a-47bc-9862-5081f1a77826)

This product costs $40,000 COP, expressed in cents is 4000000 and the tax of this product, expressed in cents, is 760000.

What we assume is that Vendure in GraphQL is concatenating these values 4000000 + 760000 = 4000000760000

On the other hand, when we enter a variant to check the tax, the admin-ui correctly calculates the price with tax. We assume that this calculation is based on the price and the calculation is done correctly by the frontend (Angular):

![image](https://github.com/vendure-ecommerce/vendure/assets/6515879/5ff4573f-55e6-4fba-a95c-0df8a8253785)

**Comment by michaelbromley** [comment] 2023-11-17 10:03
I've spent some more time trying to reproduce this:

- Used MySQL to match your environment
- Configured server to use `BigIntMoneyStrategy`
- Set default channel defaultCurrencyCode to COP
- changed standard tax rate to several different values
- tried with both tax-inclusive & exclusive pricing in the default channel settings

I'm not seeing the error. So looking at the code paths involved in calculating the tax-inclusive price of a variant, we can look at the `ProductPriceApplicator` class:

https://github.com/vendure-ecommerce/vendure/blob/fee995c967c5487e979e374802f651ce3120db6d/packages/core/src/service/helpers/product-price-applicator/product-price-applicator.ts#L88-L94

This is making a call to the configured `ProductVariantPriceCalculationStrategy`. Do you have a custom one defined?

**Comment by michaelbromley** [comment] 2023-11-17 14:54
Are you able to run the server locally in debug mode and set a breakpoint in the `product-price-applicator.js` file in your node_modules, and then step through and see where the price gets concatenated?

**Comment by daniel-lxs** [comment] 2023-11-17 21:55
Hello, the problem was happening on a deployed docker container, I tried replicating the problem but couldn't, I had a feeling that the image we were using was the problem, we changed from node:18-alpine to 21-alpine3.18 and that seems to have fixed the issue, maybe something with that image was causing the problem but I am not sure.

**Comment by michaelbromley** [comment] 2023-11-20 07:41
Wow that's bizarre! I really cannot begin to understand what might have caused this, that was fixed by changing the docker image 😱 

The reason the default strategy uses a different rounding method is to keep backwards compatibility with Vendure v1.x behaviour. Both approaches could be considered valid.

I'm going to close this now since we don't have a reliable reproduction. If it ever re-occurs and you have any other insight into related changes, we can reopen.

**Comment by michaelbromley** [comment] 2023-11-21 08:51
Reproduction: https://github.com/carathorys/money-strategy-error

**Comment by daniel-lxs** [comment] 2023-11-21 13:47
The amounts shown in the reproduction and the ones we had are the result of the sum of the two numbers instead of the product: `Math.round(num1 + num2)`.
Also I would try and change the version of node used on the docker image and see if this error only happens with versions < 18.

**Comment by michaelbromley** [comment] 2023-11-21 16:10
OK, thanks to the reproduction repo from @carathorys, I was able to get to the bottom of this:

It only happens when the custom MoneyStrategy is set via a plugin's `configuration` function. When directly setting the strategy in the VendureConfig object, it will work.

The reason that it breaks is that:

1. During bootstrap, in the `preBootstrapConfig()` function which is responsible for assembling the final config object, we have a call to `setMoneyStrategy`: https://github.com/vendure-ecommerce/vendure/blob/9b6dce696fe251a609d99ac34e464a1dff1a01ad/packages/core/src/bootstrap.ts#L153
2. However, this call is made _before_ the line that collects all the config settings from plugins: https://github.com/vendure-ecommerce/vendure/blob/9b6dce696fe251a609d99ac34e464a1dff1a01ad/packages/core/src/bootstrap.ts#L159
3. For this reason, when `setMoneyStrategy()` is called, the custom strategy defined in the plugin is not yet known to Vendure. The [`setMoneyStrategy()` function](https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/entity/set-money-strategy.ts#L8) is responsible for setting up the the TypeORM column definition for all money columns, including (importantly for this issue) the **transformer functions**
4. So when storing as a `bigint`, the value is returned from the DB as a `string` type like `'12345'`. The `transformer.from` function of the BigIntMoneyStrategy should then coerce that numeric string into a `number`.
5. However, due to the ordering issue outlined in 1 & 2 above, the transformers are never registered. Thus all addition operations are performed on strings, not numbers, resulting in the concatenation behaviour.

The solution in the referenced commit is to switch the order of operations in the bootstrap sequence to ensure we have collected all the plugin configs before we set the money strategy.

**Closed** 2023-11-21 16:10 UTC
Labels: type: bug 🐛
