### ISSUE TITLE
After creating product with variants, product variants tab stuck on loading state | Admin-ui

### ISSUE THREAD

**Issue by AntonZhuravel99** [vendure-ecommerce/vendure#517] opened 2020-10-20 13:16 UTC
**Description**
After you created a new product with some variants, shows the loading state on the product variants event after getting it from the API
**NOTE**: bug only reproduced after creating a new product, if you reload the page or go tho edit it will work fine

**To Reproduce**
1. Go to /admin/catalog/products
2. Click on "new product"
3. Create a product with few products variants
4. Save
5. Click on "product variants" tab

**Current behavior**
infinite loading state 

**Expected behavior**
should show the product variants after loading

**Version**
vendure 0.16.1

**Additional context**
Stuck on loading state
![image](https://user-images.githubusercontent.com/26551279/96590312-86527780-12ee-11eb-8b48-e386533cbec3.png)

**Comment by michaelbromley** [comment] 2020-11-03 16:24
Hi, I can't reproduce this behaviour on the current demo.vendure.io/admin (v0.16.2)

Can you try with 0.16.2 and see if you still see this error?

**Comment by AntonZhuravel99** [comment] 2020-11-03 16:32
Also can't reproduce in on demo.vendure.io/admin, but its still happens on my admin (v0.16.2), and there is no any errors in the console

**Comment by michaelbromley** [comment] 2020-11-04 09:40
Tried it in another project running 0.16.2, but still cannot reproduce. Any other information you can provide? Browser/OS? What is happening in the network tab when you click "create"?

**Comment by michaelbromley** [comment] 2021-01-08 15:59
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Closed by michaelbromley** 2021-01-08 15:59 UTC
Labels: type: bug 🐛
