### ISSUE TITLE
error.unrecognized-authentication-strategy

### ISSUE THREAD

**Issue by jmahesh626** [vendure-ecommerce/vendure#1892] opened 2022-11-22 05:58 UTC
**To Reproduce**
1. Go to vendure-config.ts within it add a 
adminAuthenticationStrategy: [
                    new AWSAuthenticationStrategy(),
        ],
2. Create a new class named AWSAuthenticationStrategy which implements AuthenticationStrategy
I followed the External Authentication 'Google' content
I used AccessToken as input and AWS Cognito URL to fetch the json and converted the key to pem and verified the token

```ts
 import {
    AuthenticationStrategy,
    ExternalAuthenticationService,
    Injector,
    RequestContext,
    User,
} from '@vendure/core';

import {
    CognitoUserPool,
    CognitoUserAttribute,
    CognitoUser,
} from 'amazon-cognito-identity-js';

import { JwtRsaVerifier } from "aws-jwt-verify";


import {
    verify,
    decode

} from 'jsonwebtoken';

// const jwkToPem=require('jwk-to-pem');


import fetch from 'node-fetch';

import { DocumentNode } from 'graphql';
import gql from 'graphql-tag';
import {JWK} from "jwk-to-pem";

export type AWSAuthData = {
    token:string;
};

export class AWSAuthenticationStrategy implements AuthenticationStrategy<AWSAuthData> {
    name: 'my_auth';
    private externalAuthenticationService: ExternalAuthenticationService;
    
    defineInputType(): DocumentNode {
        return gql`
        input AWSAuthInput {
            token: String!
        }
    `;
    }
    async authenticate(ctx: RequestContext,data: AWSAuthData): Promise<string | false | User> {

        var resultToken:any=[];
    

        const result = await fetch(`https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_rtybyNhsEsBZL/.well-known/jwks.json`);
        const value:any = result.json();


        let pems = [];
        if (result != null) {
            const keys = value['keys'];
            for (var i = 0; i < keys.length; i++) {
                //Convert each key to PEM
                var key_id = keys[i].kid;
                var modulus = keys[i].n;
                var exponent = keys[i].e;
                var key_type = keys[i].kty;
                var jwktoPem:JWK= { kty: key_type, n: modulus, e: exponent };
                var pem=  jwktoPem;
                pems[key_id] = pem;
            }
            console.log(pems);

            var decodedJwt = decode(data.token, { complete: true });
            var kid:any|string = decodedJwt?.header.kid;
            pem = pems[kid];

            console.log(pem);
         //  resultToken =verify(data.token,pem);
          //console.log(resultToken);           

        //   const user = await this.externalAuthenticationService.findCustomerUser(ctx, this.name, payload.sub);
        //   if (user) {
        //       return user;
        //   }
        return this.externalAuthenticationService.createCustomerAndUser(ctx, {
            strategy: this.name,
            externalIdentifier: 'AWS',
            verified: false,
            emailAddress: 'v@gmail.com',
            firstName: 'Vivek',
            lastName: 'Kognure',
        });
        }
           return resultToken;
    }

    onLogOut ? (ctx: RequestContext, user: User): Promise<void> {
    throw new Error('Method not implemented.');
    }
    init(injector: Injector) {
    // The ExternalAuthenticationService is a helper service which encapsulates much
    // of the common functionality related to dealing with external authentication
    // providers.
    this.externalAuthenticationService = injector.get(ExternalAuthenticationService);
}
    destroy ?: (() => void | Promise<void>) | undefined;

}
```

**Expected behavior**
It should get Access Token as input and Create a User in AWS Cognito UserPool if already not exist
 
**Environment (please complete the following information):**
 - @vendure/core version: 1.8.2
 - Nodejs version: 16.14.1
 - Database (mysql/postgres etc):mysql
**Additional context**
I am fetching information of User from AWS cognito once I get Access Token from Angular front end

**Comment by michaelbromley** [comment] 2022-11-23 16:11
Thanks for adding more detail to the report.

What I'm still missing is the part about what actually happens.

- what error do you see?
- what are the exact steps required to reproduce that error? I.e. the specific API call that results in the error.

**Comment by michaelbromley** [comment] 2023-01-05 12:49
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Closed by michaelbromley** 2023-01-05 12:49 UTC
