### ISSUE TITLE
Cannot GET /graphql 

### ISSUE THREAD

**Issue by AshotN** [vendure-ecommerce/vendure#260] opened 2020-02-11 08:11 UTC
**Describe the bug**
I followed the documentation on setting up Vendure, and when I do `yarn start` everything seems ok, but it periodically logs 

`[run:server] error 2/11/20, 12:06 AM - [Vendure Server] Cannot GET /graphql`

I also get a few 
`[run:server] error 2/11/20, 12:06 AM - [Vendure Server] Cannot GET /precache-manifest.bca02e595d9a8c8f7efe37311f48f052.esm.js`

But I can access the Admin UI and everything seems to work so far.

**To Reproduce**
`yarn start` 

**Expected behavior**

**Environment (please complete the following information):**
```
"@vendure/admin-ui-plugin": "0.8.1",
"@vendure/asset-server-plugin": "0.8.1",
"@vendure/core": "0.8.1",
"@vendure/email-plugin": "0.8.1",
"sqlite3": "4.1.1"
```
 - Nodejs version: `v13.7.0`
 - Database (mysql/postgres etc): `sqlite3 that was setup for me`

**Comment by AshotN** [comment] 2020-02-11 09:33
I setup Falcon/Diety and in the process the error seemed to stop happening. I'm not sure what I did.

This issue can be closed, but I'll leave it open just in case there is some discussion to be had.

**Comment by michaelbromley** [comment] 2020-02-11 09:36
Hi!

`[run:server] error 2/11/20, 12:06 AM - [Vendure Server] Cannot GET /graphql` indicates that something is making a GET request to the `/graphql` endpoint. Do you have something running which might be doing that? Was it coming from the Admin UI in the browser?

**Comment by AshotN** [comment] 2020-02-11 09:46
The odd thing is I was using the admin UI perfectly fine. I have no idea what would be making the requests if not the admin UI. 

I have been trying different e-commerce platforms, namely saleor and reactioncommerce. I couldn't set them up to work, but I don't know if by chance one of them was making requests to the same port or something odd. (Thanks for making something that I could actually get working)

Overall was odd, but it seems to have stopped for whatever reason. Sorry I can't give more helpful info :(

**Comment by michaelbromley** [comment] 2020-02-11 09:54
> Thanks for making something that I could actually get working

Great feedback - I also had a lot of trouble setting up some other e-commerce frameworks while I was doing research. One of my major goals is making it easy to get started.

Another possible cause of the issue is if you previously had an app running on the same origin (ie `localhost:3000`) which installed a service worker, which can keep running and making requests. The fact that it stopped after setting up Falcon suggests this may have been the reason.

I'll close this now. Have fun using Vendure 👍

**Closed by michaelbromley** 2020-02-11 09:54 UTC
Labels: type: bug 🐛
