### ISSUE TITLE
Cannot create Promotion without conditions

### ISSUE THREAD

**Issue by mariusa** [vendure-ecommerce/vendure#790] opened 2021-03-24 11:31 UTC
**Describe the bug**
Cannot create Promotion without conditions

**To Reproduce**
https://demo.vendure.io/admin/marketing/promotions/create

Add action which would apply to all products/orders, eg
![2021-03-24_13-27](https://user-images.githubusercontent.com/1283842/112303562-15e8c180-8ca5-11eb-99b6-787bf19fec9b.png)

Cannot save until a condition is added

**Expected behavior**
Be able to save the promo without conditions

**Comment by michaelbromley** [comment] 2021-03-24 11:56
Hi,

This is actually the intended behaviour - a Promotion needs either a condition or a coupon code. Can you describe your use case where you want promotions applied unconditionally?

**Comment by mariusa** [comment] 2021-03-24 12:08
Sure:

* 20% off site-wide (eg black friday)
* free shipping during Easter

Btw, would also be useful to select collections and/or products, not just product variants.

**Comment by michaelbromley** [comment] 2021-03-24 12:16
OK, got it. In that case I'd recommend you create your own [custom PromotionCondition](https://www.vendure.io/docs/developer-guide/promotions/#creating-custom-conditions) which always returns true. It would look like this:

```ts
export const universalPromotionCondition = new PromotionCondition({
    description: [{ languageCode: LanguageCode.en, value: 'Applies the promotion to all Orders}' }],
    code: 'universal_condition',
    args: {},
    check(ctx, order, args) {
        return true
    },
});
```

> Btw, would also be useful to select collections and/or products, not just product variants

Agreed. Again, you can create your own custom conditions which implement this logic for now, since we don't ship with those ones.

**Comment by mariusa** [comment] 2021-03-24 12:45
I see, thanks. Should the issue remain open as a feature request?

**Comment by michaelbromley** [comment] 2021-03-24 12:48
I'll close it and you can create a separate one for the feature request - keeps things cleaner.

**Closed by michaelbromley** 2021-03-24 12:48 UTC
Labels: type: bug 🐛
