### ISSUE TITLE
searchresult price error in listPriceIncludesTax false

### ISSUE THREAD

**Issue by BeepLoveKarki** [vendure-ecommerce/vendure#708] opened 2021-02-13 05:47 UTC
In case of channel having listPriceIncludesTax false, search result doesn't show up corrected price. Price without tax gets showed always. This seems a bug. See the screenshots here:

![Screenshot (720)](https://user-images.githubusercontent.com/29729738/107842959-275dc480-6def-11eb-9be5-14c9dd3326d1.png)
![Screenshot (721)](https://user-images.githubusercontent.com/29729738/107842961-29c01e80-6def-11eb-9496-3d9ca3d31051.png)

**Comment by michaelbromley** [comment] 2021-02-15 09:30
So in your example, the "Sanitizer Big" variant has it's price specified in the Admin UI price input as `9040`?

**Comment by BeepLoveKarki** [comment] 2021-02-15 11:02
Yes. Exactly.

**Comment by michaelbromley** [comment] 2021-02-17 13:38
I cannot reproduce this:

![image](https://user-images.githubusercontent.com/6275952/108211921-9576f400-712d-11eb-8c45-761084ee7c13.png)
![image](https://user-images.githubusercontent.com/6275952/108211972-a6276a00-712d-11eb-9174-4800801d8a0b.png)

Note the price of the cheapest laptop: 129900 excluding tax, 155880 including tax. This also matches up with the result from the `search` query.

**Comment by michaelbromley** [comment] 2021-04-07 19:43
I'm closing this because there as there is no reproduction. If anyone else runs into this and can reliably reproduce, please let me know and I'll re-open.

**Closed by michaelbromley** 2021-04-07 19:43 UTC
Labels: type: bug 🐛
