### ISSUE TITLE
Impossible to have a "not set" value in the list of customfields

### ISSUE THREAD

**Issue by giosueDelgado** [vendure-ecommerce/vendure#1710] opened 2022-08-10 12:16 UTC
**Describe the bug**
When we create a customfield we can set that the value must be in a list of values.
But if the field is nullable obviously there isn't a value inside it and in the ADMIN-UI it seem that the first item is selected.
So we want to show a "Not set" option (also empty value is ok) 

AS a workaround I create an empty string value in the list that is the Not set option. But when I save It force to me that is not a valid selection.

SO I think there are two bugs:

1. In the admin-ui we need to manage a not set option in the select component and not automatically show the first selected if is null the customfield.
2. Allow an empty string value in the list because at the moment when you save the value you cannot have an empty string.

**To Reproduce**
Example of custom field that I create for the workaround:
```
{
    name: "language",
    type: "string",
    defaultValue: "",
    label: [
      { languageCode: LanguageCode.it, value: "Lingua" },
      { languageCode: LanguageCode.en, value: "Language" },
    ],
    options: [
      {
        value: "",
        label: [
          { languageCode: LanguageCode.it, value: "Non impostato" },
          { languageCode: LanguageCode.en, value: "Not set" },
        ],
      },
      {
        value: "it_IT",
        label: [
          { languageCode: LanguageCode.it, value: "Italiano" },
          { languageCode: LanguageCode.en, value: "Italian" },
        ],
      },
      {
        value: "en_US",
        label: [
          { languageCode: LanguageCode.it, value: "Inglese" },
          { languageCode: LanguageCode.en, value: "English" },
        ],
      },
      {
        value: "fr_FR",
        label: [
          { languageCode: LanguageCode.it, value: "Francese" },
          { languageCode: LanguageCode.en, value: "French" },
        ],
      },
    ],
  },


```

**Expected behavior**
See description (or write me on slack for more details)

**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs version
 - Database (mysql/postgres etc): postgres

**Additional context**
![image](https://user-images.githubusercontent.com/11545723/183898676-5a8832b5-aff8-45ac-bfdb-f6da56387bb4.png)

**Comment by michaelbromley** [comment] 2022-08-15 14:48
Tested on current master, with this config:

```ts
customFields: {
        Customer: [
            {
                name: 'language',
                type: 'string',
                nullable: true,
                label: [
                    { languageCode: LanguageCode.it, value: 'Lingua' },
                    { languageCode: LanguageCode.en, value: 'Language' },
                ],
                options: [
                    {
                        value: 'it_IT',
                        label: [
                            { languageCode: LanguageCode.it, value: 'Italiano' },
                            { languageCode: LanguageCode.en, value: 'Italian' },
                        ],
                    },
                    {
                        value: 'en_US',
                        label: [
                            { languageCode: LanguageCode.it, value: 'Inglese' },
                            { languageCode: LanguageCode.en, value: 'English' },
                        ],
                    },
                    {
                        value: 'fr_FR',
                        label: [
                            { languageCode: LanguageCode.it, value: 'Francese' },
                            { languageCode: LanguageCode.en, value: 'French' },
                        ],
                    },
                ],
            },
        ],
    },
}
```

I cannot reproduce. Setting `nullable: true` will cause the UI to display an empty option by default: 
![image](https://user-images.githubusercontent.com/6275952/184657815-55cec18e-5ad1-4b7d-aa36-d1c9b83c79de.png)

Perhaps you ran into a situation where the customField is first given a defaultValue of `''`, which will cause all existing Customers to have that value. Then, if you later try to change it to `nullable: true` and save an existing Customer (which already had the value set to `''`), you will encounter an error.

**Comment by giosueDelgado** [comment] 2022-08-17 20:58
Ok, I try made a configuration with nullable: true I think in this case fix my issue

**Comment by michaelbromley** [comment] 2022-09-19 10:15
OK, closing this as it seems fixed. Please follow up if it turns out we missed something.

**Closed by michaelbromley** 2022-09-19 10:15 UTC
Labels: type: bug 🐛
