### ISSUE TITLE
Unable to create new shipping method

### ISSUE THREAD

**Issue by anmol1905** [vendure-ecommerce/vendure#1845] opened 2022-10-18 01:59 UTC
I am unable to create a new shipping method. Please check it as soon as possible
The create button is not getting enabled

![image](https://user-images.githubusercontent.com/77231592/196317337-654a5017-2849-47de-869f-ddc010294685.png)

**Comment by anmol1905** [comment] 2022-10-18 12:25
Update on this,
I changed the shipping price and then reverted it back to 0. Same as the default eligibility checker and now it works.

If I don't change the default values then it doesn't let me save

**Comment by michaelbromley** [comment] 2022-10-18 13:01
OK thanks for the extra info. By the way can you confirm what version of Vendure you are working with?

**Comment by anmol1905** [comment] 2022-10-19 07:59
It is 1.6.3

**Comment by michaelbromley** [comment] 2022-10-19 12:41
ok. Are you able to upgrade to v1.7.4 and see if the problem still exists?

**Comment by michaelbromley** [comment] 2022-10-24 08:38
I believe this issue was fixed in v1.7.3: https://github.com/vendure-ecommerce/vendure/blob/master/CHANGELOG.md#173-2022-09-24

I cannot reproduce on current master. I'm going to close this but please let me know if you still run into it after updating to the latest version.

**Closed by michaelbromley** 2022-10-24 08:38 UTC
Labels: type: bug 🐛
