### ISSUE TITLE
Problems with the installation

### ISSUE THREAD

**Issue by hmoralesluis** [vendure-ecommerce/vendure#293] opened 2020-04-01 16:50 UTC
On the installation process I get this error, with npm and with yarn too

{"message":"An error occurred when installing dependencies. Try running with `--log-level info` to diagnose.","command":"yarnpkg add --exact --ignore-engines @vendure/core @vendure/email-plugin @vendure/asset-server-plugin @vendure/admin-ui-plugin sqlite3 --cwd D:\\Node App\\vendrure_family\\vendure_node13","context":{}}
error Command failed.

I use Windows, my Node Version is v12.16.1

**Comment by michaelbromley** [comment] 2020-04-01 18:52
Hi,

Did you try the suggestion on running with `--log-level info` to see more detailed output? That might help point to the cause of the error.

**Comment by michaelbromley** [comment] 2020-04-15 07:01
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Closed by michaelbromley** 2020-04-15 07:01 UTC
Labels: type: bug 🐛

**Comment by basith374** [comment] 2020-11-15 09:11
I also have this issue. I've tried running with `--log-level info` but to no use.

```
$ npx @vendure/create my-shop --log-level info
npx: installed 96 in 4.953s

Welcome to @vendure/create v0.17.0!

Let's configure a new Vendure project. First a few questions:

✔ Which database are you using? › MySQL
✔ What's the database host address? … localhost
✔ What port is the database listening on? … 3306
✔ What's the name of the database? … vendure
✔ What's the database user name? … root
✔ What's the database password? … ******
✔ Which programming language will you be using? › TypeScript
✔ Populate with some sample product data? … no / yes
✔ What identifier do you want to use for the superadmin user? … superadmin
✔ What password do you want to use for the superadmin user? … superadmin

Setting up your new Vendure project in /home/ubuntu/my-shop
This may take a few minutes...

  ⠏ Installing dependencies
    → Installing @vendure/core, @vendure/email-plugin, @vendure/asset-server-plugin, @vendure/admin-ui-plugin, mysql, typescript@4.0.3
    Generating app scaffold
    Initializing server
  ⠋ Installing dependencies
  ✖ Installing dependencies
    → An error occurred when installing dependencies.
    Generating app scaffold
    Initializing server
{"message":"An error occurred when installing dependencies.","command":"npm install --save --save-exact --loglevel error @vendure/core @vendure/email-plugin @vendure/asset-server-plugin @vendure/admin-ui-plugin mysql typescript@4.0.3","context":{}}
```

npm version `6.14.5`
node version `12.18.1`

**Comment by michaelbromley** [comment] 2020-11-15 18:51
Hmm... Not much info there still. Try log level `verbose` and see what you get. Warning, there Wil be a *lot* of output, but hopefully some helpful pointer to the underlying issue.

**Comment by mohammedghazal** [comment] 2021-05-31 10:49
> I also have this issue. I've tried running with `--log-level info` and I got the following response.
> 
> ```
> $ npx @vendure/create my-shop --log-level info
> npx: installed 96 in 4.953s
> 
> Welcome to @vendure/create v0.17.0!
> 
> Let's configure a new Vendure project. First a few questions:
> 
> ✔ Which database are you using? › MySQL
> ✔ What's the database host address? … localhost
> ✔ What port is the database listening on? … 3306
> ✔ What's the name of the database? … vendure
> ✔ What's the database user name? … root
> ✔ What's the database password? … ******
> ✔ Which programming language will you be using? › TypeScript
> ✔ Populate with some sample product data? … no / yes
> ✔ What identifier do you want to use for the superadmin user? … superadmin
> ✔ What password do you want to use for the superadmin user? … superadmin
> 
> Setting up your new Vendure project in /home/ubuntu/my-shop
> This may take a few minutes...
> 
>   ⠏ Installing dependencies
>     → Installing @vendure/core, @vendure/email-plugin, @vendure/asset-server-plugin, @vendure/admin-ui-plugin, mysql, typescript@4.0.3
>     Generating app scaffold
>     Initializing server
>   ⠋ Installing dependencies
>   ✖ Installing dependencies
>     → An error occurred when installing dependencies.
>     Generating app scaffold
>     Initializing server
> {"message":"An error occurred when installing dependencies.","command":"npm install --save --save-exact --loglevel error @vendure/core @vendure/email-plugin @vendure/asset-server-plugin @vendure/admin-ui-plugin mysql typescript@4.0.3","context":{}}
> ```
> 
> npm version `6.14.5`
> node version `12.18.1`
> ubuntu 18.04 server

did u solve this issue?
