### ISSUE TITLE
Error on fresh install of v2.0.4: node_modules/i18next/index.d.ts:835:69 - error TS1005: '?' expected.

### ISSUE THREAD

**Issue by yasserlens** [vendure-ecommerce/vendure#2291] opened 2023-07-17 11:38 UTC
**Describe the bug**
The following error shows up on "npm run build" on a fresh project out of "npx @vendure/create"
```
➜  vendure-2.0.4 npm run build

> vendure-2.0.4@0.1.0 build
> tsc

node_modules/i18next/index.d.ts:835:69 - error TS1005: '?' expected.

835   : _FallbackNamespace extends (infer UnionFallbackNs extends string)[]                                             ~

Found 1 error.

```

**To Reproduce**
1. npx @vendure/create my-app
2. cd my-app
3. npm run build

**Expected behavior**
Error should not be there 

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.4
 - Nodejs version v18.11.0
 - Database (mysql/postgres etc): Postgres

**Additional context**
None

**Comment by pbalakri** [comment] 2023-07-18 03:27
What version of node are you using?

**Comment by yasserlens** [comment] 2023-07-18 09:33
It's in the bug report - Nodejs version v18.11.0

**Comment by Caryntjen** [comment] 2023-07-23 14:49
Same issue on Windows, 
@vendure/core version: 2.0.4
Nodejs version v16.15.1
Database (mysql/postgres etc): Postgres

**Comment by michaelbromley** [comment] 2023-07-25 07:22
Thanks, I'll look into this.

**Comment by michaelbromley** [comment] 2023-10-18 06:46
Closing this as I have been unable to reproduce. If it is still an issue please comment and I'll reopen.

**Closed by michaelbromley** 2023-10-18 06:46 UTC
Labels: type: bug 🐛
