### ISSUE TITLE
Add metadata parameter to Logger

### ISSUE THREAD

**Issue by ttournie** [vendure-ecommerce/vendure#936] opened 2021-06-17 07:43 UTC
**Is your feature request related to a problem? Please describe.**
Right now, it's not possible to use send Json metadata in the Logger (for me I use the context as 'any').
It's really useful to get extra metadata on some log, specially when using Datadog along with Winston

**Describe the solution you'd like**
A new optional parameter 'metadata' in all Logger function that can take an object should do the trick

**Comment by michaelbromley** [comment] 2022-07-01 12:51
Closing as a duplicate of #1444

**Closed by michaelbromley** 2022-07-01 12:51 UTC
