### ISSUE TITLE
(core) Entity updatedAt not updated

### ISSUE THREAD

**Issue by jacobfrantz1** [vendure-ecommerce/vendure#2400] opened 2023-09-18 17:41 UTC
**Describe the bug**
Since v2, updatedAt is no longer updated when using many of vendure's mutations.

I think this typeorm issue describes the problem: https://github.com/typeorm/typeorm/issues/9219

To summarize what I think is going on; if updatedAt is present, as it would be when loaded from the database, its value is used instead of generating the value from the current time. It is only updated when calling repository.update or if you set updatedAt to undefined before saving the entity.

We are using updatedAt for syncing orders to our shipping provider.

**To Reproduce**
1. Change order state to Modifiying with the admin-ui and cancel the modification
2. See that the updatedAt time was not updated.

**Expected behavior**
Mutations that modify an entity should have an updated updatedAt time.

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.6
 - Nodejs version: 16.20.1
 - Database: postgres

**Comment by devi-prsd** [comment] 2023-12-28 06:24
+1

**Comment by michaelbromley** [comment] 2024-06-17 08:45
I cannot reproduce this in the current version in testing (2.2.5):


https://github.com/vendure-ecommerce/vendure/assets/6275952/a5b05e1f-58d2-4448-95f3-d6dc6911c09e

Therefore I'm going to close this issue. If it is still an issue for anyone, please comment and we can reopen if needed.

**Closed by michaelbromley** 2024-06-17 08:45 UTC
Labels: type: bug 🐛

**Comment by jacobfrantz1** [comment] 2024-08-26 19:24
I looked back at this and tried removing my typeorm patch. This issue still occurs, the example you show in the video uses the translatable-saver, which manually handles changing the updatedAt time. Specifically, changing an order's state through fulfillment or through the modify button in the admin ui does not update the updatedAt time.
