### ISSUE TITLE
item still showing in admin UI after deletion

### ISSUE THREAD

**Issue by gggiiia** [vendure-ecommerce/vendure#268] opened 2020-02-23 12:11 UTC
**Describe the bug**

**To Reproduce**
1. Go to products on admin UI
2. Click on delete button of a random product
3. delete the selected product
4. get a successful deletion notification
5. look at the list
6. the deleted item id still there :sob: 

**Expected behavior**
after deleting something it should be removed from the UI list without the need to reload the list

**Environment (please complete the following information):**
 - @vendure/core version: 0.9
 - Nodejs version is this even needed? 
 - Database (mysql/postgres etc): SQlite

**Additional context**

**Comment by michaelbromley** [comment] 2020-02-25 11:02
Hi there, can you check whether you are also running the worker process? In the product list view, the list is based on the search index, which gets updated on the worker process. If the worker is not running, the index will not be updated. Please verify whether or not this is the case.

**Comment by michaelbromley** [comment] 2020-03-19 08:48
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, let me know and I'll re-open it.

**Closed by michaelbromley** 2020-03-19 08:48 UTC
Labels: type: bug 🐛

**Comment by zifahm** [comment] 2020-05-29 08:04
@michaelbromley  I think im facing the same scenario as well, I checked if my worker is up, and it seems like it is.

**Comment by michaelbromley** [comment] 2020-05-29 08:19
@zifahm ok, can you provide details of your environment:

* vendure version
* node version
* db type

and steps to reliably reproduce?

**Comment by zifahm** [comment] 2020-05-29 08:27
vendure: 0.12.5
node: 12.17.0
db: postgres 11.8

delete a product with variants. Also try disabling the variant individually and deleting it.

**Comment by zifahm** [comment] 2020-05-29 09:07
I think cascading delete might fix this? Looks like its a soft delete in my db

**Comment by michaelbromley** [comment] 2020-05-29 13:51
@zifahm The product list in the Admin UI is based on the `search` query, which uses a separate index and is not constrained by a foreign-key relation to the Product table, so a cascade would not work here. Instead, an event listener in the DefaultSearchPlugin listens to "deleted" events and is supposed to update the search index accordingly.

I'll look into it and see if I can reproduce.
