### ISSUE TITLE
Active order returns null when combined with other queries

### ISSUE THREAD

**Issue by StampixSMO** [vendure-ecommerce/vendure#2097] opened 2023-03-23 11:15 UTC
**Describe the bug**
When requesting multiple queries from the server, one of which is the `activeOrder`, the active order returns `null`.

**To Reproduce**
1. Make sure you have an active order
2. Run this query
    ```graphql
	query test {
		activeOrder {
			id
		}
		activeChannel {
			id
		}
	}
    ```

**Expected behavior**
Active order not to be null.

**Environment (please complete the following information):**
 - @vendure/core version: 1.9.3
 - Nodejs version: 16
 - Database (mysql/postgres etc): postgres

**Additional context**

If you remove the `activeChannel` query, the active order gets returned properly.

**Comment by Job-madi** [comment] 2023-09-13 06:57
Hey @michaelbromley, could I be assigned to this issue?

**Comment by michaelbromley** [comment] 2024-09-20 13:04
I spent some time investigating this issue (I even live streamed the debugging session here https://www.youtube.com/live/f0srTEUqr5Y?si=VQT78GlA7KXXQ60U&t=361)

The root cause is that the [AuthGuard.canActivate](https://github.com/vendure-ecommerce/vendure/blob/5f165e872b56a5d6f2f21a63280c18f64ee33ae3/packages/core/src/api/middleware/auth-guard.ts#L45) executes for both resolvers, `activeOrder` and `activeChannel` in a non-deterministic order.

For any given query field there are 3 relevant steps as relates to this issue:

1. AuthGuard.canActivate runs for that field
2. Inside that method, we create a `RequestContext` object. Part of that is determining the state of the `authorizedAsOwnerOnly` property. This differs depending on whether the target field's resolver has an `@Allow(Permission.Owner)` decorator.
3. The newly-created `RequestContext` object gets attached to the `req` object so it can be picked up by the `@Ctx()` decorator in the resolver.

Step 3 is where the bug arises. There are 2 possible sequences, and which one occurs is non-deterministic:

**happy path**
1. AuthGuard runs for the `activeOrder` query. `authorizedAsOwnerOnly` gets set to `true`
2. Resolver executes for `activeOrder`.  `authorizedAsOwnerOnly === true` and the order gets returned.
3. AuthGuard runs for `activeChannel`. `authorizedAsOwnerOnly` gets set to `false` (because it does not have the Permission.Owner decorator)
4. Resolver executes for `activeChannel`

**error path**
1. AuthGuard runs for the `activeOrder` query. `authorizedAsOwnerOnly` gets set to `true`
2. AuthGuard runs for `activeChannel`. `authorizedAsOwnerOnly` gets set to `false` 
3. Resolver executes for `activeOrder`.  `authorizedAsOwnerOnly === false` (it was last set in the `activeChannel` auth guard) and no order is returned
4. Resolver executes for `activeChannel`

I am currently exploring alternative approaches to how we store the RequestContext and make it available to resolvers & controller methods.

**Closed** 2024-09-20 14:14 UTC
Labels: type: bug 🐛, contributions welcome

**Comment by casperiv0** [comment] 2024-09-20 14:32
Thank you, Michael!
