### ISSUE TITLE
Custom fields localeText with Relation breaks update

### ISSUE THREAD

**Issue by drobytskyi** [vendure-ecommerce/vendure#2708] opened 2024-02-28 16:32 UTC
**Describe the bug**
I want to add custom fields to Product, here is the code, which I'm adding:

**`vendure-config.ts`**

**To Reproduce**
```
customFields: {
    Product: [
      {
        name: "alternatives",
        list: true,
        type: "relation",
        entity: Product,
        label: [
          {
            languageCode: LanguageCode.en,
            value: "Alternative Variants",
          },
        ],
        nullable: true,
      },
      {
        name: "composition",
        type: "localeText",
        nullable: true,
        list: false
      },
      {
        name: "washing",
        type: "localeText",
        nullable: true,
        list: false
      },
      {
        name: "modelSize",
        list:false,
        nullable: true,
        type: "relation",
        entity: Asset,
        label: [
          {
            languageCode: LanguageCode.en,
            value: "Model & Size",
          },
        ],
      },
    ],
  },
```

Getting Error
```
[server] error 2/28/24, 2:35 AM - [ExceptionsHandler] Cannot set properties of undefined (setting 'alternatives')
[server] TypeError: Cannot set properties of undefined (setting 'alternatives')
```

**Expected behavior**

Updating fields in the admin UI

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.7
 - Nodejs version: 20
 - Database (mysql/postgres etc): postgres

**Additional context**

**Comment by brmk** [comment] 2024-02-28 22:14
maybe a duplicate of https://github.com/vendure-ecommerce/vendure/issues/2680 ?

**Closed** 2024-03-04 14:45 UTC
Labels: type: bug 🐛
