### ISSUE TITLE
`search` endpoint returns duplicated results for translated products

### ISSUE THREAD

**Issue by tschortsch** [vendure-ecommerce/vendure#2197] opened 2023-05-26 18:42 UTC
**Describe the bug**
When I translate an existing product to another language the `search` endpoint (`shop-api` as well as `admin-api`) returns the translated product variants in both languages in the `items` field. This only happens when the `languageCode` param is set to another language than the default language. This behavior is also visible in the Admin UI when the `Group by product` switch is deactivated in the product list.

**To Reproduce**
1. Enable multiple languages in 'Global settings'
1. Go to 'Catalog > Products'
2. Edit an existing product and translate it to another language
3. Go to 'Catalog > Products' again and select a non-default language in the locale switcher
4. Disable the 'Group by product' switch

**Expected behavior**
You should only see the product variants in the selected language

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0-beta.2
 - Nodejs version: 18
 - Database (mysql/postgres etc): sqlite

**Comment by WeAreHaus** [comment] 2023-09-28 08:34
We are running Vendure 2.0.5 and are also experiencing issues with duplicated products when using `search`. It happens regardless if we use the `langCode` param and regardless of which language is set as default. We have about 400 products translated into both Swedish and English and use paginated queries to fetch them (12 at a time). 

Sometimes, one of the products on the next page is the same as the products on the previous page - i.e. the same product is fetched twice but on different pages. This seems to be an issue when the product name is identical or the price is identical. We tried to sort by name, then price or price, then name, but to no avail.

The instance is running the DefaultSearchPlugin, if that makes any difference.

When do you think it's possible to have a fix for this bug?

**Comment by michaelbromley** [comment] 2023-09-28 09:41
@WeAreHaus I just put this on the backlog to take a look at for the next patch release.

If you are able to set up a minimal reproduction repo, it would make it about 10x more likely that I can get a fix for that patch :)

**Comment by WeAreHaus** [comment] 2023-09-29 08:47
Great, thank you!

We managed to solve it by loading all products into the browser and do the pagination there instead. I'm a little pressed for time at the moment but will try to create a reproduction repo soon.

**Comment by busyfingers** [comment] 2023-11-07 14:01
Hi @michaelbromley 

I have created a reproduction repo for this issue here: https://github.com/WeAreHaus/reproduction-vendure-issue-2197
(I'm the previous poster, just posting from a different account this time) :)

I haven't been able to reproduce the duplicated first and last product when paginating the results using the Vendure demo data. Unfortunately I cannot share the actual data we use but I will continue to look into that part, and maybe it should also be a different issue.

Let me know if you need any more information. Thank you in advance!

**Comment by michaelbromley** [comment] 2023-11-14 10:57
@busyfingers thank you for the reproduction! Looking into this now...

**Comment by michaelbromley** [comment] 2023-11-14 14:56
I believe this is the same issue that is addressed in this PR:

- https://github.com/vendure-ecommerce/vendure/pull/2515

**Closed** 2023-11-22 21:26 UTC
Labels: type: bug 🐛, @vendure/core
