### ISSUE TITLE
External Authentication blocked when logging in on two different channels

### ISSUE THREAD

**Issue by mattgills** [vendure-ecommerce/vendure#961] opened 2021-06-30 14:56 UTC
**Describe the bug**
Loosely related to updates from V1.0.3 and #926.

The updates from the above bug fix look good and appear to work on preliminary testing.  In addition to that testing, I attempted to login to a second channel with the same SSO auth method.  During the login, I saw the server log:
```
QueryFailedError: duplicate key value violates unique constraint "REL_3f62b42ed23958b120c235f74d"
```
This was the result of an insert customer attempt, which failed because there was already a customer associated with that email and related user.  Upon looking further into the `ExternalAuthenticationService`, I saw that `findCustomerUser` failing to retrieve a customer via line 49:
```
const customer = await this.customerService.findOneByUserId(ctx, user.id);
```
After further inspection into the `customerService.findOneByUserId` function, it appears to be caused by the fact that `filterOnChannel` is set to true.   I believe that this should actually try to update the existing customer's channel.

**To Reproduce**
1. Create Channel A and Channel B
2. Login to Channel A with an external auth method
3. Login to Channel B with the same email and same external auth method
3. You should see an error that attempts to insert a duplicate customer into the database

**Expected behavior**
If a user logs into another channel with the same email and auth method, then the customer's channels should be updated to include the new one.

**Environment (please complete the following information):**
 - @vendure/core version: 1.0.3
 - Nodejs version: 14.17.0
 - Database (mysql/postgres etc): postgres

**Additional context**
N/A

**Comment by michaelbromley** [comment] 2021-07-12 09:29
Hi Matt,

I've been looking in to this issue this morning but I can't reproduce. Here's what I did:

1. I have a test AuthenticationMethod that looks like this:
    ```ts
    export class SSOShopAuthenticationStrategy implements AuthenticationStrategy<SSOAuthData> {
    readonly name = 'ssoShop';
    private externalAuthenticationService: ExternalAuthenticationService;

    init(injector: Injector) {
        this.externalAuthenticationService = injector.get(ExternalAuthenticationService);
    }

    defineInputType(): DocumentNode {
        return gql`input SSOAuthInput { email: String! }`;
    }

    async authenticate(ctx: RequestContext, data: SSOAuthData): Promise<User | false> {
        const user = await this.externalAuthenticationService.findCustomerUser(ctx, this.name, data.email);
        if (user) {
            return user;
        }

        return this.externalAuthenticationService.createCustomerAndUser(ctx, {
            strategy: this.name,
            externalIdentifier: data.email,
            emailAddress: data.email,
            firstName: 'test',
            lastName: 'customer',
            verified: true,
        });
    }
    }
    ```
2. I set up 2 Channels, A and B
3. I login on Channel A using "test@test.com". This creates a new User and Customer.
4. I log out and then log in with the same email address on Channel B

At step 4 I don't get any error because the same User entity as created in step 3 above is returned from the  `findCustomerUser` method. Therefore no new Customer is created.

For the error to occur as you describe, I guess that the same User entity is not used when creating a new Customer? Can you confirm this?

**Comment by Kalmac** [comment] 2022-10-25 16:08
Hello @michaelbromley,

I have the same problem as @mattgills and done some searches with the same workflow :

1. authenticate  in my customStrategy :
```typescript
  async authenticate(
    ctx: RequestContext,
    data: KeycloakAuthData,
  ): Promise<User | false> {
      const userInfo = await this._keycloakService.validateUserJwt(data.token);

      const user = await this._externalAuthenticationService.findCustomerUser(
        ctx,
        this.name,
        userInfo.sub,
      );
      if (user) {
        return user;
      }

      return this._externalAuthenticationService.createCustomerAndUser(ctx, {
        strategy: this.name,
        externalIdentifier: userInfo.sub,
        emailAddress: userInfo.email,
        verified: userInfo.email_verified,
        firstName: userInfo.given_name,
        lastName: userInfo.family_name,
      });
  }
```

2. I setup 2 channels A & B
3. I call `authenticate` using a user X token with `vendure-token` in header from channel A. This creates a new User and Customer (the customer is linked to channel A & default)
4. I call `authenticate` using the same user with `vendure-token` from channel B => `QueryFailedError: duplicate key value violates unique constraint`

The  `findCustomerUser` calls `findOneByUserId` with default third argument `filterOnChannel = true`. The query returns no customer for channel B and tries to insert a new Customer with duplicate id.

Is there a workaround or a fix for this use case ?

**Comment by michaelbromley** [comment] 2022-11-14 20:13
@Kalmac I added a new argument to the `findCustomerUser` method to allow you to control the channel filtering. This is in v1.8.3.

**Closed by michaelbromley** 2022-11-14 20:13 UTC
Labels: type: bug 🐛
