### ISSUE TITLE
[admin-ui] Missing type in OrderDetail

### ISSUE THREAD

**Issue by d46** [vendure-ecommerce/vendure#232] opened 2019-12-23 12:44 UTC
**Describe the bug**

At 7.0, after running `yarn bootstrap && yarn build` then executing `yarn codegen` makes a diff in `OrderDetail` in `admin-ui` `genereted-types.ts`.
It removes `Fulfillment` type from OrderDetail. Therefore `admin-ui` not able to compile successfully. Might be some code insertions missing about on `OrderDetail`. By that, it throws an error on every related OrderDetail lines which are looking for `Fulfillment` in `admin-ui`. It looks like after release 7 OrderDetail takes `Fulfillments` instead of `Fulfillment`. If you also getting this error in your local I will find a solution.

 - @vendure/core version: 7.0
 - Nodejs version 10.14
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment] 2019-12-23 13:24
Hi,

Thanks for the report. Yes, I can reproduce this. It was caused by this commit https://github.com/vendure-ecommerce/vendure/commit/c33f1f61ee7f9d7b467479199cfa84eef6eb58ab from 5 days ago which refactored a GraphQL operation but then I neglected to run the codegen afterwards so missed the issue.

The fix would be to run the codegen, then update [this line](https://github.com/vendure-ecommerce/vendure/blob/master/packages/admin-ui/src/app/order/components/fulfillment-detail/fulfillment-detail.component.ts#L15) to `Fulfillments`. 

If you would like to contribute a fix for this, then a PR would be very welcome.

**Closed** 2019-12-26 08:54 UTC
Labels: type: bug 🐛
