### ISSUE TITLE
'An error occurred, could not delete Collection' [admin-ui] on real-world-vendure

### ISSUE THREAD

**Issue by agustif** [vendure-ecommerce/vendure#298] opened 2020-04-06 11:46 UTC
**Describe the bug**
I can't delete default seeded collections from real-world-vendure.

I get a notification on the AdminUI:  An error occurred, could not delete Collection
Frontend WS Error:
`sockjs.js:2999 WebSocket connection to 'ws://localhost:3000/sockjs-node/358/4upa4qjb/websocket' failed: WebSocket is closed before the connection is established.
`
Log Errors:
```
[run:server] error 4/6/20, 1:25 PM - [TypeORM] Query error: Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed, "DELETE FROM "collection" WHERE "id" = ?" -- [4]
[run:server] error 4/6/20, 1:25 PM - [TypeORM] Query error: Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed, "DELETE FROM "collection" WHERE "id" = ?" -- [7]
[run:server] error 4/6/20, 1:25 PM - [Vendure Server] Cannot GET /sw.js
[run:server] error 4/6/20, 1:26 PM - [Vendure Server] Cannot GET /sw.js
[run:server] error 4/6/20, 1:26 PM - [TypeORM] Query error: Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed, "DELETE FROM "collection" WHERE "id" = ?" -- [4]
[run:server] error 4/6/20, 1:27 PM - [TypeORM] Query error: Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed, "DELETE FROM "collection" WHERE "id" = ?" -- [4]
```
**To Reproduce**
1. Go to 'Collections List'
2. Click on 'three vertical dots (more options?) -> delete'
3. Click delte on modal confirmation UI

**Expected behavior**
The collection should be deleted? Maybe it's childs too.?

**Environment (please complete the following information):**
 - @vendure/core version: v0.10.0
 - Nodejs version 12.13
 - Database (mysql/postgres etc): postgres (PostgreSQL) 12.2

**Comment by michaelbromley** [comment] 2020-04-06 11:52
Duplicate of #297

**Closed by michaelbromley** 2020-04-06 11:52 UTC
Labels: type: bug 🐛
