### ISSUE TITLE
Issue: Inconsistency in Decimal Point Precision in `product_variant_price` Table

### ISSUE THREAD

**Issue by xabru** [vendure-ecommerce/vendure#2490] opened 2023-10-28 07:51 UTC
**Describe the bug**
I've noticed an inconsistency in the `product_variant_price` table within the Vendure project's PostgreSQL database. The `price` column in this table lacks decimal points, while the product manager displays prices with decimal points. This discrepancy is causing confusion. I'm seeking guidance on how to retrieve the prices as displayed in the product manager from the PostgreSQL database.

**To Reproduce**
1. Navigate to the `product_variant_price` table in the PostgreSQL database.
2. Observe the values in the `price` column.

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.1
 - Nodejs version: 20
 - Database (mysql/postgres etc): PostgreSQL 16.0

**Screenshots**
![image](https://github.com/vendure-ecommerce/vendure/assets/55867760/9bd38c0f-927b-44d7-8d05-a212d8aa1899)

![image](https://github.com/vendure-ecommerce/vendure/assets/55867760/9dc64093-1435-4cf9-80e9-4eb29cc49971)

**Comment by oidt** [comment] 2023-10-29 09:32
https://docs.vendure.io/guides/core-concepts/money/ does this explain it for you?

**Comment by michaelbromley** [comment] 2023-10-30 08:59
I'm closing this as "working as intended" :)

**Closed by michaelbromley** 2023-10-30 08:59 UTC
Labels: type: bug 🐛
