### ISSUE TITLE
Missing Error when registrating as an existing customer

### ISSUE THREAD

**Issue by TitusAzevedo** [vendure-ecommerce/vendure#2180] opened 2023-05-15 17:32 UTC
When registrating as a new customer with the nativ auth strategy, using an exsiting email the result is successful. The user is not created and it's return value is not distinguishable from a proper mutation.

**Comment by michaelbromley** [comment] 2024-06-20 08:37
Closing as a duplicate of

- https://github.com/vendure-ecommerce/vendure/issues/746

**Closed by michaelbromley** 2024-06-20 08:37 UTC
Labels: type: bug 🐛
