### ISSUE TITLE
ctx.req.app.get is not available in JobQueue after ctx.serialize() and ctx.deserialize()

### ISSUE THREAD

**Issue by hsensh** [vendure-ecommerce/vendure#3028] opened 2024-08-22 14:35 UTC
**Describe the bug**
ctx.req.app.get is not available in JobQueue after ctx.serialize() and ctx.deserialize()

**To Reproduce**
1. Create a Job
2. Pass the serialized context to it
3. Deserialize it
4. ctx.req.app.get is not a function

**Expected behavior**
Context should be identical before and after serialization

**Environment (please complete the following information):**
 - @vendure/core version: 3.0.1
 - Nodejs version: 18
 - Database (mysql/postgres etc): mysql

**Comment by michaelbromley** [comment] 2024-08-22 14:43
> Context should be identical before and after serialization

This is unfortunately not technically feasible because functions like `app.get()` cannot be serialized. This is also the case for self-referential data structures which is also something that heavily features in the Express `req` and `res` objects. So during serialization we need to protect against these circular references also.

You can see the implementation of this here: https://github.com/vendure-ecommerce/vendure/blob/master/packages/core/src/api/common/request-context.ts#L249

So I'm going to close this as "working as intended". 

But perhaps you can elaborate on why you need access to `req.app.get()` in your job - perhaps there is another way to achieve your goal?

**Closed by michaelbromley** 2024-08-22 14:43 UTC
Labels: type: bug 🐛

**Comment by hsensh** [comment] 2024-08-22 14:48
I am working on an ERP Next plugin and sometimes I need access to the general context (ie. not linked to a specific channel), while still having the target channel for processing.

Example: I am synchronizing products for channel A, in the synchronize function, I need access to the full context with full access permissions all while having a reference to the channel that I am currently working on to handle specific use cases for it (ie. sometimes I need to get all products and other times products with a specific channel).

Before I was doing it inside the server directly, and it was working fine, but now I need to put it inside the queue and this is where I hit a wall. I can just pass in the required channel in the arguments but that would require a lot of refactoring to the core code.

**Comment by hsensh** [comment] 2024-08-22 14:58
Event this is not working:

```
let ctx = RequestContext.deserialize(job.data.ctx);

        let user = ctx.activeUserId
        ? await this.userService.getUserById(ctx, ctx.activeUserId)
        : undefined;

        ctx = await this.requestContextService.create({
          req: ctx.req,
          apiType: "admin",
          user: user,
        });

        ctx.req?.app?.set(
          "channel",
          await this.channelService.getChannelFromToken(job.data.channelToken)
        );
```

`ctx.req?.app?.set is not a function`

**Comment by michaelbromley** [comment] 2024-08-22 15:34
Can you explain at a high level what this code is for?

```
 ctx.req?.app?.set(
          "channel",
          await this.channelService.getChannelFromToken(job.data.channelToken)
        );
```

**Comment by michaelbromley** [comment] 2024-08-22 15:46
OK, so you are using the `req.app` as a kind of global data store for that request right?

You could possibly achieve the same by directly setting & reading properties on the `req` object directly:

```ts
ctx.req.myKey = 'foo'
```

this should be successfully serialized & deserialized.

However to me this seems somewhat hacky. I wonder if there is just a better approach. I think this would potentially be solved if we allowed custom fields on the Session object. In that way you'd be able to store the custom field data in the server context, and then retrieve the custom fields from the worker context.

Related:

- https://github.com/vendure-ecommerce/vendure/issues/2069

**Comment by hsensh** [comment] 2024-08-22 15:51
Yes! That would be perfect. I followed this approach for the lack of a better one. Should I make a feature request?

**Comment by michaelbromley** [comment] 2024-09-02 10:28
Yes, a feature request would be welcome.
