### ISSUE TITLE
[2.0.0-beta] problem with e2e tests (exit code 139)

### ISSUE THREAD

**Issue by alexisvigoureux** [vendure-ecommerce/vendure#2142] opened 2023-04-24 12:56 UTC
**Describe the bug**
I'm testing the new Vendure 2.0.0-beta.1.
I have a `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)` when I run the e2e tests with **Jest**. It works on Vendure version 1.9.5.
Have there been any breaking changes in `@vendure/testing`?

After investigation, the problem appears in the server.init(..)

**To Reproduce**

```
import { LanguageCode, mergeConfig } from '@vendure/core'
import { createTestEnvironment, PostgresInitializer, registerInitializer } from '@vendure/testing'
import { testConfig as defaultTestConfig } from '@vendure/testing/lib/config/test-config'

const testConfig = mergeConfig(defaultTestConfig, {
  dbConnectionOptions: {
    type: 'postgres',
    logging: false,
    database: 'test',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT ? +process.env.DB_PORT : 5432,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
  },
  defaultLanguageCode: LanguageCode.fr,
})
registerInitializer('postgres', new PostgresInitializer())

describe('v2', () => {
  const { server } = createTestEnvironment({
    ...testConfig,
    plugins: [],
  })

  beforeAll(async () => {
    await server.init({
      initialData: {
        defaultLanguage: LanguageCode.fr,
        defaultZone: 'Europe',
        countries: [{ name: 'France', code: 'FR', zone: 'Europe' }],
        taxRates: [{ name: 'Zero Tax', percentage: 0 }],
        shippingMethods: [],
        collections: [],
        paymentMethods: [],
      },
    })
  }, 120000)

  afterAll(async () => {
    jest.resetAllMocks()
    await server.destroy()
  })

  it('test', () => {
    expect(1 + 1).toBe(2)
  })
})
```

**Expected behavior**
That the e2e tests work when moving from Vendure 1.9 to 2.0

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0-beta.1
 - Nodejs version: 18.15
 - Database (mysql/postgres etc): postgres

**Comment by michaelbromley** [comment] 2023-04-28 09:10
Hi,

is there any more information available? If you turn on logging for example:

```
LOG=1 yarn test
```

In my experience I had a setup with Jest and I ran into issues with ESM support. I ended up moving over to Vitest.

**Comment by alexisvigoureux** [comment] 2023-05-03 13:41
Hi, no more information with LOG=1
With Node 18: `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`
With Node 16: `Error: You need to run with a version of node that supports ES Modules in the VM API. See https://jestjs.io/docs/ecmascript-modules` , which confirms the ESM track

We did a POC with Vitest on 1 e2e test and it works, so we will think about migration

**Comment by williamrijksen** [comment] 2023-05-25 20:17
Hi,

I recently updated my Vendure application to the Vendure v2 beta version and encountered the same issue. I was wondering if there have been any updates regarding this issue? Additionally, I would appreciate any guidance or suggestions on how I can resolve this problem.

**Comment by Zizitto** [comment] 2023-05-29 11:42
+1

**Comment by yh0an** [comment] 2023-06-20 14:36
+1

**Comment by gdarchen** [comment] 2023-06-20 15:08
We have been investigating so far and we are still stuck, but let's sum up our conclusions tracked [here](https://discord.com/channels/1100672177260478564/1119274743036661850/1119274743036661850).

We have transitioned our test configuration from Jest towards Vitest, and still faced this issue about unhandled errors.
We were then able to reproduce the bug on the `v2` of Vendure on a smaller project than ours, cf. [this draft PR](https://github.com/vendure-ecommerce/real-world-vendure/pull/48).

The trouble seems to be located when we try to load plugins in the tests as follows:

```ts
const { server, adminClient, shopClient } = createTestEnvironment({
    ...testConfig(),
    plugins: [ReviewsPlugin],
});
```

The issue only appears if the following `customField` is declared in the plugin:
```ts
config.customFields.Product.push({
    name: 'featuredReview',
    label: [{ languageCode: LanguageCode.en, value: 'Featured review' }],
    public: true,
    type: 'relation',
    entity: ProductReview,
    ui: { tab: 'Reviews', component: 'review-selector-form-input' },
});
```

Using the `LOG=1` argument, we were able to have a clearer message about what's happening:
```
error 6/20/23, 3:49 PM - [TypeOrmModule] Unable to connect to the database. Retrying (2)...
TypeORMError: Entity metadata for Product#customFields.featuredReview was not found. Check if you specified a correct entity object and if it's connected in the connection options.
    at <path>/real-world-vendure/src/metadata-builder/EntityMetadataBuilder.ts:1089:23
```

We can't figure out why so far, but the `customField` could not be created. 🤷

**Comment by michaelbromley** [comment] 2023-07-13 11:31
I'm tracing the source of this problem and so far I've landed at this line in TypeORM's `EntityMetadataBuilder.computeInverseProperties` method:

![image](https://github.com/vendure-ecommerce/vendure/assets/6275952/1712fd51-d2b4-458f-b5b9-b3ffd6a892a3)

On running the first test suite, `m.target === relation.type` evaluates to `true` and it works.

On the second test suite, it evaluates to `false` even though they both seem to point to the same `ProductReview` class.

**Comment by gdarchen** [comment] 2023-07-13 11:57
Hey @michaelbromley!
Yes that's exactly what we have discovered so far and the point where we have been stuck. 

Actually, `m.target` and `relation.type` seem to be object and not primitive types, so the `===` on the first test works because the objects must refer to the same instance, and maybe in the second round, the object provided is a shallow copy?

**Comment by michaelbromley** [comment] 2023-07-13 12:29
Noting that I managed to get the real-world-vendure repo example working if I do not disable the `threads` and `isolate` option:

```
 threads: true,
 isolate: true,
```

(note that these are the default values so you can just omit them)

If you do this, you will then run into the issue that each test is listening on the same port. We solve this in the e2e tests in this repo by dynamically assigning a new port to each test run: https://github.com/vendure-ecommerce/vendure/blob/1cb676ab082bb3a48a652eefada83304ce36f655/e2e-common/test-config.ts#L40-L57

My suspicion right now is that when running in a non-isolated mode, some side effect is happening between test suite runs which is causing the problem. I have no idea currently what that is though.

**Closed** 2023-12-15 13:44 UTC
Labels: type: bug 🐛, v2 beta issue
