### ISSUE TITLE
npm init / npx script failing

### ISSUE THREAD

**Issue by timojokinen** [vendure-ecommerce/vendure#202] opened 2019-11-12 09:54 UTC
**Describe the bug**
The init scripts on the website don't work. Settings don't matter. It fails every time.

**To Reproduce**
1. npx @vendure/create my-app / npm init @vendure my-app
2. Select any database provider
3. Use TypeScript or JavaScript
4. Use populate data or not
5. Script fails every time with following error
`{"message":"An error occurred when installing dependencies. Try running with `--log-level info` to diagnose.","command":"npm install --save --save-exact --loglevel error @vendure/core @vendure/email-plugin @vendure/asset-server-plugin @vendure/admin-ui-plugin sqlite3","context":{}}`

**Expected behavior**
Create a new vendure project

**Environment (please complete the following information):**
 - @vendure/core version:
 - Nodejs version: 10.16.3
 - Database (mysql/postgres etc): any

**Comment by michaelbromley** [comment] 2019-11-12 10:16
Hi,

Can you also specify your OS and Vendure version? I cannot reproduce with Vendure 0.5.1 on Windows:

```
$ npx @vendure/create@0.5.1 my-app
npx: installed 83 in 22.046s

Welcome to @vendure/create v0.5.1!

Let's configure a new Vendure project. First a few questions:

√ Which database are you using? » SQLite
√ Which programming language will you be using? » TypeScript
√ Populate with some sample product data? ... no / yes

Setting up your new Vendure project in C:\Development\temp\my-app
This may take a few minutes...

  √ Installing dependencies
  √ Generating app scaffold
  / Initializing server
  importing [========================================] 100% 0.0s  Importing: Modern Cafe Chair
  √ Initializing server

Success! Created a new Vendure server at C:\Development\temp\my-app

We suggest that you start by typing:

    cd my-app
    yarn start

Happy hacking!
```

You can also try the suggestion from the error message:
```
npx @vendure/create my-app --log-level info
```

This might yield some more useful information so we can get to the bottom of the issue.

**Comment by timojokinen** [comment] 2019-11-12 10:22
I'm on MacOS Mojave 10.14.6
also tried as superuser - still doesn't work.
Here's the full log:

```sudo npx @vendure/create my-app --log-level info
npx: installed 83 in 3.388s

Welcome to @vendure/create v0.5.1!

Let's configure a new Vendure project. First a few questions:

✔ Which database are you using? › SQLite
✔ Which programming language will you be using? › TypeScript
✔ Populate with some sample product data? … no / yes

Setting up your new Vendure project in /Users/Timo/Documents/my-app
This may take a few minutes...

  ⠸ Installing dependencies
    → Installing @vendure/core, @vendure/email-plugin, @vendure/asset-server-plu
…
    Generating app scaffold
    Initializing server
  ⠦ Installing dependencies
    → Installing @vendure/core, @vendure/email-plugin, @vendure/asset-server-plu
…
    Generating app scaffold
    Initializing server
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/Timo/Documents/my-app/node_modules/@angular/compiler-cli/node_modules/fsevents/build'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/Timo/Documents/my-app/node_modules/@angular/compiler-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/Timo/Documents/my-app/node_modules/@angular/compiler-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/Timo/Documents/my-app/node_modules/@angular/compiler-cli/node_modules/fsevents
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Timo/Documents/my-app/node_modules/@angular/compiler-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/Timo/Documents/my-app/node_modules/@angular/compiler-cli/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Timo/Documents/my-app/node_modules/@angular/compiler-cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Timo/Documents/my-app/node_modules/@angular/compiler-cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Timo/Documents/my-app/node_modules/@angular/compiler-cli/node_modules/fsevents
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Timo/  ⠇ Installing dependencies
    → Installing @vendure/core, @vendure/email-plugin, @vendure/asset-server-plu
…
    Generating app scaffold
    Initializing server
  ⠼ Installing dependencies
    → Installing @vendure/core, @vendure/email-plugin, @vendure/asset-server-plu
…
    Generating app scaffold
    Initializing server
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents/build'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/Timo/Documents/my-app/node_modules/watchpack/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
  ⠙ Installing dependencies
    → Installing @vendure/core, @vendure/email-plugin, @vendure/asset-server-plu
…
    Generating app scaffold
    Initializing server
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents/build'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/Timo/Documents/my-app/node_modules/webpack-dev-server/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_  ⠧ Installing dependencies
    → Installing @vendure/core, @vendure/email-plugin, @vendure/asset-server-plu
…
    Generating app scaffold
    Initializing server
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/Timo/Documents/my-app/node_modules/bcrypt/build'
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/Timo/Documents/my-app/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/Timo/Documents/my-app/node_modules/bcrypt/lib/binding" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/Timo/Documents/my-app/node_modules/bcrypt
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/Timo/Documents/my-app/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/Timo/Documents/my-app/node_modules/bcrypt/lib/binding --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Timo/Documents/my-app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/Timo/Documents/my-app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Timo/Documents/my-app/node_modules/bcrypt
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modu  ⠼ Installing dependencies
    → Installing @vendure/core, @vendure/email-plugin, @vendure/asset-server-plu
…
    Generating app scaffold
    Initializing server
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.6 install script.
  ✖ Installing dependencies
    → An error occurred when installing dependencies. Try running with `--log-le
…
    Generating app scaffold
    Initializing server
{"message":"An error occurred when installing dependencies. Try running with `--log-level info` to diagnose.","command":"npm install --save --save-exact --loglevel error @vendure/core @vendure/email-plugin @vendure/asset-server-plugin @vendure/admin-ui-plugin sqlite3","context":{}}
➜  Documents >....
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modu  ⠼ Installing dependencies
    → Installing @vendure/core, @vendure/email-plugin, @vendure/asset-server-plu
…
    Generating app scaffold
    Initializing server
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.6 install script.
  ✖ Installing dependencies
    → An error occurred when installing dependencies. Try running with `--log-le
…
    Generating app scaffold
    Initializing server
{"message":"An error occurred when installing dependencies. Try running with `--log-level info` to diagnose.","command":"npm install --save --save-exact --loglevel error @vendure/core @vendure/email-plugin @vendure/asset-server-plugin @vendure/admin-ui-plugin sqlite3","context":{}}```

**Comment by michaelbromley** [comment] 2019-11-12 10:37
This looks like a permissions error related to npm. See https://github.com/angular/angular-cli/issues/6848

and take a look at https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

Let me know if these resources help you resolve this.

**Comment by timojokinen** [comment] 2019-11-12 12:28
I reinstalled node with nvm which made it work, thanks!

**Closed** 2019-11-12 12:29 UTC
Labels: type: bug 🐛
