### ISSUE TITLE
Could not load the "sharp" module using the win32-x64 runtime

### ISSUE THREAD

**Issue by meyvan** [vendure-ecommerce/vendure#2975] opened 2024-07-27 02:32 UTC
**Describe the bug**
When I try to create a new installation by following https://docs.vendure.io/guides/getting-started/installation/ guide I get the followinf error:

```
Error: Could not load the "sharp" module using the win32-x64 runtime
[worker] Possible solutions:
[worker] - Ensure optional dependencies can be installed:
[worker]     npm install --include=optional sharp
[worker]     yarn add sharp --ignore-engines
[worker] - Ensure your package manager supports multi-platform installation:
[worker]     See https://sharp.pixelplumbing.com/install#cross-platform
[worker] - Add platform-specific dependencies:
[worker]     npm install --os=win32 --cpu=x64 sharp
[worker] - Consult the installation documentation:
```

**To Reproduce**
1. Use Windows 10/11
2. Follow guide https://docs.vendure.io/guides/getting-started/installation/
3. Run `npm run dev`

**Expected behavior**
Should run smoothly

**Environment (please complete the following information):**
 - @vendure/core version: [v3.0.0](https://github.com/vendure-ecommerce/vendure/releases/tag/v3.0.0)
 - Nodejs version : v18.19.1
 - Database (mysql/postgres etc): postgres

**Additional context**

Sharp is only required if someone is using this strategy: https://docs.vendure.io/reference/core-plugins/asset-server-plugin/sharp-asset-preview-strategy 

Why install it in the first place ? If someone wants to use it, let them install and use the strategy

Proposed Solution: Remove Sharp library as default and update docs to reflect the same

**Comment by VitoorFranca** [comment] 2024-07-27 05:45
Install sharp if you are using asset server strategy:

`npm install --include=optional sharp`
or
`yarn add sharp --ignore-engines`

**Comment by meyvan** [comment] 2024-07-27 12:43
> Install sharp if you are using asset server strategy:
> 
> `npm install --include=optional sharp` or `yarn add sharp --ignore-engines`

Mate two things:

1. Even if I run the above it's still the same issue
2. I'm not using the `SharpAssetPreviewStrategy`, im using the `S3AssetStorageStrategy` 

My question is why is included as part of core packages ? Since the entire architecture is strategy based why not let the end user install it IF AND ONLY IF they use `SharpAssetPreviewStrategy` ?

**Comment by ziban** [comment] 2024-07-29 22:50
> Install sharp if you are using asset server strategy:
> 
> `npm install --include=optional sharp` or `yarn add sharp --ignore-engines`

It's a mess when doing automated builds because you depend on what's defined in package.json

**Comment by michaelbromley** [comment] 2024-07-30 08:06
Hi @meyvan, thanks for the report

Regarding the error itself, it may be the same as reported here

- https://github.com/lovell/sharp/issues/3926

> My question is why is included as part of core packages ? Since the entire architecture is strategy based why not let the end user install it IF AND ONLY IF they use SharpAssetPreviewStrategy ?

When you use `@vendure/create` we do include some non-core plugins that (usually) make the starting experience smoother.

- AssetServerPlugin
- EmailPlugin
- AdminUiPlugin

We do not ship any other asset preview strategy than the sharp one, which means that if we didn't include it in a standard installation, then if you try to upload images we would not be able to create previews. 

Can you try updating to Node v20 and see if that makes any difference?

**Comment by meyvan** [comment] 2024-07-30 10:20
> We do not ship any other asset preview strategy than the sharp one, which means that if we didn't include it in a standard installation, then if you try to upload images we would not be able to create previews.
> 
> Can you try updating to Node v20 and see if that makes any difference?

@michaelbromley I get it.

But here is my visible confusion:

![Screenshot (2)](https://github.com/user-attachments/assets/84bae90d-5325-46f7-b1d6-bbab7d1e618d)

I see previews being made as optional params, which led me to assume, those are in fact optional

Second, the left panel shows Sharp Preview Strategy similar to AssetStorage and LocalStorage and underneath it. It led me to believe SharpPreview is a separate strategy and not part of Assets Storage.

Maybe can it be included as a submenu underneath AssetStorageStragety ?

**Comment by meyvan** [comment] 2024-07-30 10:21
I was under the assumption that if no preview related configurations are sent in, then no image will be transformed

**Comment by meyvan** [comment] 2024-07-30 10:25
Still getting the same error mate, tried 20 and 22

**Comment by meyvan** [comment] 2024-07-30 10:34
Got it. To anyone who is using windows, use the below for local development and make sure to install the linux based when you are deploying. Not a great solution but the bug from Sharp as mentioned by @michaelbromley  makes it as a necessity
```
npm install sharp
npm install --force @img/sharp-win32-x64
```

**Comment by ziban** [comment] 2024-07-30 12:17
@meyvan please reopen it. I'm experiencing the same issue on a linux machine, and I think having a long term solution helps. 

@michaelbromley it breaks between version 2.1.9 and 2.2.0. I had to upgrade from an earlier version to use a plugin and ran into this error. 
![Screen Shot 2024-07-30 at 3 14 33 PM](https://github.com/user-attachments/assets/428da149-85f8-4da4-873a-92cf9a61fff0)

**Comment by michaelbromley** [comment] 2024-07-31 01:17
in v2.2.0 we upgraded the Sharp version, which is why the issue now appears.

I think a work-around could be that we add the `--include=optional`  flag in the `@vendure/create` install command. The strange thing is that I don't run into this when testing locally. I'll have to see how I can reproduce and therefore test any fixes.

**Comment by ziban** [comment] 2024-07-31 05:27
Some thoughts on reproducing the error: 
1. Maybe installing an earlier version(2.0/2.1) then upgrading might cause the issue. 
2. Using yarn - was able to solve the issue by moving to npm, and running `npm install --cpu=x64 --os=linux --libc=glibc sharp` and `npm install --include=optional sharp`

**Comment by dlhck** [comment] 2024-10-04 20:38
> 2\. Using yarn - was able to solve the issue by moving to npm, and running `npm install --cpu=x64 --os=linux --libc=glibc sharp` and `npm install --include=optional sharp`

@ziban did that resolve the issue? In case it did I would like to add it to our docs. Thanks!

**Comment by ziban** [comment] 2024-10-08 08:17
Yeah it resolved the issue, but I'm not certain if it will work for everyone.

**Comment by floze** [comment] 2024-10-14 19:30
FWIW and because I haven't seen it mentioned yet, using `yarn install --ignore-engines` properly installs the runtime as well, without having to add sharp to the package explicitly.

**Comment by dlhck** [comment] 2024-10-15 15:27
It seems that this is an issue that is massively dependent on the OS. Right now there is no clear solution for that, a lot of the commands in the comments are a good approach to solve it. I will close this issue for now, if it comes up again we can re-open it at this point.

**Closed by dlhck** 2024-10-15 15:27 UTC
Labels: type: bug 🐛, @vendure/core, @vendure/asset-server-plugin, P2: important, status: research needed 🔍
