### ISSUE TITLE
worker server doesn't get stopped

### ISSUE THREAD

**Issue by azliabdullah** [vendure-ecommerce/vendure#150] opened 2019-08-31 17:35 UTC
**Describe the bug**
Worker server didn't get stop when stopping vendure-server

**To Reproduce**
1. run vendure dev server using `yarn dev-server:start`
2. let everything start and running.
3. hit ctrl+c stop vendure-server

**Expected behavior**
- both vendure-server and worker-server stopped

**Actual behavior**
- vendure-server stopped but worker-server is not.
- has to kill worker-server port by `sudo kill -9 $(sudo lsof -t -i:3020)

**Environment (please complete the following information):**
 @vendure/core version: 0.2.0 (master)
Nodejs version: v12.9.0
Database (mysql/postgres etc): mariadb 10.3

**Additional context**
not big issue, but it leads to some issues (and confusing as well) when restarting vendure-server.

**Comment by michaelbromley** [comment] 2019-09-02 07:12
Thanks for the report. I also run into this while developing, and I think it is a problem with the `concurrently` package which is used to run the 2 processes.

Will investigate further when more critical issues are resolved.

**Comment by michaelbromley** [comment] 2019-09-03 08:43
May be related to https://github.com/kimmobrunfeldt/concurrently/issues/67

**Comment by ncjones** [comment] 2019-10-17 22:11
I think the issue is in Vendure. If I run thew worker process in the foreground then send SIGINT (hit Ctrl-C) then an unhandled promise rejection is logged and the process continues to run:

```
nathan@jnx:~/Code/vendure
⇒  node src/index-worker.js 
info 10/18/19, 11:05 AM - [Vendure Worker] Bootstrapping Vendure Worker (pid: 3893)... 
info 10/18/19, 11:05 AM - [NestMicroservice] Nest microservice successfully started 
info 10/18/19, 11:05 AM - [Vendure Worker] Vendure Worker started with TCP transport at localhost:3020 
^C
(node:3893) UnhandledPromiseRejectionWarning: Error: Nest cannot find given element (it does not exist in current context)
    at ContainerScanner.findInstanceByPrototypeOrToken (/home/nathan/Code/jucygroup/jucy-vendure/node_modules/@nestjs/core/injector/container-scanner.js:24:19)
    at Object.findInstanceByPrototypeOrToken (/home/nathan/Code/jucygroup/jucy-vendure/node_modules/@nestjs/core/injector/module-ref.js:39:38)
    at Object.get (/home/nathan/Code/jucygroup/jucy-vendure/node_modules/@nestjs/core/injector/module.js:306:29)
    at TypeOrmCoreModule.<anonymous> (/home/nathan/Code/jucygroup/jucy-vendure/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:93:47)
    at Generator.next (<anonymous>)
    at /home/nathan/Code/jucygroup/jucy-vendure/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/nathan/Code/jucygroup/jucy-vendure/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:15:12)
    at TypeOrmCoreModule.onModuleDestroy (/home/nathan/Code/jucygroup/jucy-vendure/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:89:16)
    at Object.callModuleDestroyHook (/home/nathan/Code/jucygroup/jucy-vendure/node_modules/@nestjs/core/hooks/on-module-destroy.hook.js:42:35)
```

When I use PM2 to manage the Vendure processes then this issue is somewhat mitigated: it tries to send SIGINT for a few seconds then gives up and sends SIGTERM. I guess Concurrently is only sending SIGINT and not falling back to SIGTERM like PM2.

**Comment by michaelbromley** [comment] 2019-10-18 11:27
@ncjones Thanks, that was really helpful and allowed me to track down the root cause. Fix will be included in next release.

**Closed** 2019-10-18 11:26 UTC
Labels: type: bug 🐛
